# Generated by Django 3.0.4 on 2020-03-29 16:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DNSZone",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("zone_root", models.CharField(max_length=255)),
                ("last_modified", models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name="DNSZoneRecord",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ttl", models.IntegerField()),
                (
                    "zone",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="dns_grpc.DNSZone",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AddressRecord",
            fields=[
                (
                    "dnszonerecord_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="dns_grpc.DNSZoneRecord",
                    ),
                ),
                ("address", models.GenericIPAddressField()),
            ],
            bases=("dns_grpc.dnszonerecord",),
        ),
    ]
