# Generated by Django 3.0.5 on 2020-05-10 10:13

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("dns_grpc", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="addressrecord",
            name="address",
            field=models.GenericIPAddressField(verbose_name="Address (IPv4/IPv6)"),
        ),
        migrations.AlterField(
            model_name="addressrecord",
            name="auto_reverse",
            field=models.BooleanField(
                default=False, verbose_name="Automatically serve reverse PTR records"
            ),
        ),
        migrations.AlterField(
            model_name="addressrecord",
            name="record_name",
            field=models.CharField(
                default="@",
                max_length=255,
                verbose_name="Record name (@ for zone root)",
            ),
        ),
        migrations.AlterField(
            model_name="addressrecord",
            name="ttl",
            field=models.PositiveIntegerField(verbose_name="Time to Live (seconds)"),
        ),
        migrations.AlterField(
            model_name="caarecord",
            name="record_name",
            field=models.CharField(
                default="@",
                max_length=255,
                verbose_name="Record name (@ for zone root)",
            ),
        ),
        migrations.AlterField(
            model_name="caarecord",
            name="ttl",
            field=models.PositiveIntegerField(verbose_name="Time to Live (seconds)"),
        ),
        migrations.AlterField(
            model_name="cnamerecord",
            name="record_name",
            field=models.CharField(
                default="@",
                max_length=255,
                verbose_name="Record name (@ for zone root)",
            ),
        ),
        migrations.AlterField(
            model_name="cnamerecord",
            name="ttl",
            field=models.PositiveIntegerField(verbose_name="Time to Live (seconds)"),
        ),
        migrations.AlterField(
            model_name="mxrecord",
            name="record_name",
            field=models.CharField(
                default="@",
                max_length=255,
                verbose_name="Record name (@ for zone root)",
            ),
        ),
        migrations.AlterField(
            model_name="mxrecord",
            name="ttl",
            field=models.PositiveIntegerField(verbose_name="Time to Live (seconds)"),
        ),
        migrations.AlterField(
            model_name="naptrrecord",
            name="record_name",
            field=models.CharField(
                default="@",
                max_length=255,
                verbose_name="Record name (@ for zone root)",
            ),
        ),
        migrations.AlterField(
            model_name="naptrrecord",
            name="ttl",
            field=models.PositiveIntegerField(verbose_name="Time to Live (seconds)"),
        ),
        migrations.AlterField(
            model_name="nsrecord",
            name="nameserver",
            field=models.CharField(max_length=255, verbose_name="Name server"),
        ),
        migrations.AlterField(
            model_name="nsrecord",
            name="record_name",
            field=models.CharField(
                default="@",
                max_length=255,
                verbose_name="Record name (@ for zone root)",
            ),
        ),
        migrations.AlterField(
            model_name="nsrecord",
            name="ttl",
            field=models.PositiveIntegerField(verbose_name="Time to Live (seconds)"),
        ),
        migrations.AlterField(
            model_name="ptrrecord",
            name="ttl",
            field=models.PositiveIntegerField(verbose_name="Time to Live (seconds)"),
        ),
        migrations.AlterField(
            model_name="srvrecord",
            name="record_name",
            field=models.CharField(
                default="@",
                max_length=255,
                verbose_name="Record name (@ for zone root)",
            ),
        ),
        migrations.AlterField(
            model_name="srvrecord",
            name="ttl",
            field=models.PositiveIntegerField(verbose_name="Time to Live (seconds)"),
        ),
        migrations.AlterField(
            model_name="txtrecord",
            name="record_name",
            field=models.CharField(
                default="@",
                max_length=255,
                verbose_name="Record name (@ for zone root)",
            ),
        ),
        migrations.AlterField(
            model_name="txtrecord",
            name="ttl",
            field=models.PositiveIntegerField(verbose_name="Time to Live (seconds)"),
        ),
        migrations.CreateModel(
            name="SSHFPRecord",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                (
                    "record_name",
                    models.CharField(
                        default="@",
                        max_length=255,
                        verbose_name="Record name (@ for zone root)",
                    ),
                ),
                (
                    "ttl",
                    models.PositiveIntegerField(verbose_name="Time to Live (seconds)"),
                ),
                ("host_key", models.TextField()),
                (
                    "zone",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="dns_grpc.DNSZone",
                    ),
                ),
            ],
            options={
                "verbose_name": "SSHFP record",
                "verbose_name_plural": "SSHFP records",
            },
        ),
    ]
