# Generated by Django 3.0.7 on 2020-08-10 11:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dns_grpc', '0001_squashed_0018_auto_20200725_2020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dnszone',
            name='zone_root',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='reversednszone',
            name='zone_root_address',
            field=models.GenericIPAddressField(db_index=True),
        ),
        migrations.AlterField(
            model_name='reversednszone',
            name='zone_root_prefix',
            field=models.PositiveIntegerField(db_index=True, validators=[django.core.validators.MaxValueValidator(128)]),
        ),
        migrations.AlterField(
            model_name='secondarydnszone',
            name='primary',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='secondarydnszone',
            name='zone_root',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AddIndex(
            model_name='addressrecord',
            index=models.Index(fields=['record_name', 'zone'], name='dns_grpc_ad_record__22ca60_idx'),
        ),
        migrations.AddIndex(
            model_name='anamerecord',
            index=models.Index(fields=['record_name', 'zone'], name='dns_grpc_an_record__22ca60_idx'),
        ),
        migrations.AddIndex(
            model_name='caarecord',
            index=models.Index(fields=['record_name', 'zone'], name='dns_grpc_ca_record__22ca60_idx'),
        ),
        migrations.AddIndex(
            model_name='cnamerecord',
            index=models.Index(fields=['record_name', 'zone'], name='dns_grpc_cn_record__22ca60_idx'),
        ),
        migrations.AddIndex(
            model_name='dsrecord',
            index=models.Index(fields=['record_name', 'zone'], name='dns_grpc_ds_record__22ca60_idx'),
        ),
        migrations.AddIndex(
            model_name='hinforecord',
            index=models.Index(fields=['record_name', 'zone'], name='dns_grpc_hi_record__22ca60_idx'),
        ),
        migrations.AddIndex(
            model_name='locrecord',
            index=models.Index(fields=['record_name', 'zone'], name='dns_grpc_lo_record__22ca60_idx'),
        ),
        migrations.AddIndex(
            model_name='mxrecord',
            index=models.Index(fields=['record_name', 'zone'], name='dns_grpc_mx_record__22ca60_idx'),
        ),
        migrations.AddIndex(
            model_name='naptrrecord',
            index=models.Index(fields=['record_name', 'zone'], name='dns_grpc_na_record__22ca60_idx'),
        ),
        migrations.AddIndex(
            model_name='nsrecord',
            index=models.Index(fields=['record_name', 'zone'], name='dns_grpc_ns_record__22ca60_idx'),
        ),
        migrations.AddIndex(
            model_name='rprecord',
            index=models.Index(fields=['record_name', 'zone'], name='dns_grpc_rp_record__22ca60_idx'),
        ),
        migrations.AddIndex(
            model_name='srvrecord',
            index=models.Index(fields=['record_name', 'zone'], name='dns_grpc_sr_record__22ca60_idx'),
        ),
        migrations.AddIndex(
            model_name='sshfprecord',
            index=models.Index(fields=['record_name', 'zone'], name='dns_grpc_sp_record__22ca60_idx'),
        ),
        migrations.AddIndex(
            model_name='txtrecord',
            index=models.Index(fields=['record_name', 'zone'], name='dns_grpc_tx_record__22ca60_idx'),
        ),
        migrations.AddIndex(
            model_name='dynamicaddressrecord',
            index=models.Index(fields=['record_name', 'zone'], name='dns_grpc_dy_record__ef57a3_idx'),
        ),
        migrations.AddIndex(
            model_name='secondarydnszonerecord',
            index=models.Index(fields=['record_name', 'zone'], name='dns_grpc_se_record__d5b143_idx'),
        ),
    ]
