# Generated by Django 3.0.4 on 2020-03-29 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dns_grpc", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="dnszone",
            options={"verbose_name": "DNS Zone", "verbose_name_plural": "DNS Zones"},
        ),
        migrations.AddField(
            model_name="dnszonerecord",
            name="record_name",
            field=models.CharField(default="@", max_length=255),
        ),
    ]
