# Generated by Django 3.0.7 on 2020-08-10 11:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dns_grpc', '0001_squashed_0018_auto_20200725_2020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dnszone',
            name='zone_root',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='reversednszone',
            name='zone_root_address',
            field=models.GenericIPAddressField(db_index=True),
        ),
        migrations.AlterField(
            model_name='reversednszone',
            name='zone_root_prefix',
            field=models.PositiveIntegerField(db_index=True, validators=[django.core.validators.MaxValueValidator(128)]),
        ),
        migrations.AlterField(
            model_name='secondarydnszone',
            name='primary',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='secondarydnszone',
            name='zone_root',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AddIndex(
            model_name='addressrecord',
            index=models.Index(fields=['record_name', 'zone'], name='dns_grpc_ad_record__22ca60_idx'),
        ),
        migrations.AddIndex(
            model_name='dynamicaddressrecord',
            index=models.Index(fields=['record_name', 'zone'], name='dns_grpc_dy_record__ef57a3_idx'),
        ),
        migrations.AddIndex(
            model_name='secondarydnszonerecord',
            index=models.Index(fields=['record_name', 'zone'], name='dns_grpc_se_record__d5b143_idx'),
        ),
    ]
