# Generated by Django 3.1 on 2020-09-10 21:09

import as207960_utils.models
from django.db import migrations, models
import django.db.models.deletion
import dns_grpc.models


class Migration(migrations.Migration):

    dependencies = [
        ('dns_grpc', '0002_auto_20200810_1112'),
    ]

    operations = [
        migrations.CreateModel(
            name='DNSZoneUpdateSecrets',
            fields=[
                ('id', as207960_utils.models.TypedUUIDField(data_type='hexdns_zoneupdatesecret', primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('U', 'Unlimited access'), ('D', 'ACME DNS01 access')], max_length=1)),
                ('secret', models.BinaryField(default=dns_grpc.models.make_update_secret)),
            ],
        ),
        migrations.RemoveIndex(
            model_name='anamerecord',
            name='dns_grpc_an_record__22ca60_idx',
        ),
        migrations.RemoveIndex(
            model_name='caarecord',
            name='dns_grpc_ca_record__22ca60_idx',
        ),
        migrations.RemoveIndex(
            model_name='cnamerecord',
            name='dns_grpc_cn_record__22ca60_idx',
        ),
        migrations.RemoveIndex(
            model_name='dsrecord',
            name='dns_grpc_ds_record__22ca60_idx',
        ),
        migrations.RemoveIndex(
            model_name='hinforecord',
            name='dns_grpc_hi_record__22ca60_idx',
        ),
        migrations.RemoveIndex(
            model_name='locrecord',
            name='dns_grpc_lo_record__22ca60_idx',
        ),
        migrations.RemoveIndex(
            model_name='mxrecord',
            name='dns_grpc_mx_record__22ca60_idx',
        ),
        migrations.RemoveIndex(
            model_name='naptrrecord',
            name='dns_grpc_na_record__22ca60_idx',
        ),
        migrations.RemoveIndex(
            model_name='nsrecord',
            name='dns_grpc_ns_record__22ca60_idx',
        ),
        migrations.RemoveIndex(
            model_name='rprecord',
            name='dns_grpc_rp_record__22ca60_idx',
        ),
        migrations.RemoveIndex(
            model_name='srvrecord',
            name='dns_grpc_sr_record__22ca60_idx',
        ),
        migrations.RemoveIndex(
            model_name='sshfprecord',
            name='dns_grpc_sp_record__22ca60_idx',
        ),
        migrations.RemoveIndex(
            model_name='txtrecord',
            name='dns_grpc_tx_record__22ca60_idx',
        ),
        migrations.AlterField(
            model_name='account',
            name='subscription_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='addressrecord',
            name='id',
            field=as207960_utils.models.TypedUUIDField(data_type='hexdns_zoneaddressrecord', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='anamerecord',
            name='id',
            field=as207960_utils.models.TypedUUIDField(data_type='hexdns_zoneanamerecord', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='caarecord',
            name='id',
            field=as207960_utils.models.TypedUUIDField(data_type='hexdns_zonecaarecord', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='cnamerecord',
            name='id',
            field=as207960_utils.models.TypedUUIDField(data_type='hexdns_zonecnamerecord', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='dnszone',
            name='id',
            field=as207960_utils.models.TypedUUIDField(data_type='hexdns_zone', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='dnszone',
            name='resource_id',
            field=models.UUIDField(db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='dsrecord',
            name='id',
            field=as207960_utils.models.TypedUUIDField(data_type='hexdns_zonedsrecord', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='dynamicaddressrecord',
            name='id',
            field=as207960_utils.models.TypedUUIDField(data_type='hexdns_zonedynamicaddressrecord', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='hinforecord',
            name='id',
            field=as207960_utils.models.TypedUUIDField(data_type='hexdns_zonehinforecord', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='locrecord',
            name='id',
            field=as207960_utils.models.TypedUUIDField(data_type='hexdns_zonelocrecord', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='mxrecord',
            name='id',
            field=as207960_utils.models.TypedUUIDField(data_type='hexdns_zonemxrecord', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='naptrrecord',
            name='id',
            field=as207960_utils.models.TypedUUIDField(data_type='hexdns_zonenaptrrecord', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='nsrecord',
            name='id',
            field=as207960_utils.models.TypedUUIDField(data_type='hexdns_zonensrecord', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='ptrrecord',
            name='id',
            field=as207960_utils.models.TypedUUIDField(data_type='hexdns_rzoneptrrecord', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='reversednszone',
            name='id',
            field=as207960_utils.models.TypedUUIDField(data_type='hexdns_rzone', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='reversednszone',
            name='resource_id',
            field=models.UUIDField(db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='reversensrecord',
            name='id',
            field=as207960_utils.models.TypedUUIDField(data_type='hexdns_rzonensrecord', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='rprecord',
            name='id',
            field=as207960_utils.models.TypedUUIDField(data_type='hexdns_zonerprecord', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='secondarydnszone',
            name='id',
            field=as207960_utils.models.TypedUUIDField(data_type='hexdns_szone', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='secondarydnszone',
            name='resource_id',
            field=models.UUIDField(db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='secondarydnszonerecord',
            name='id',
            field=as207960_utils.models.TypedUUIDField(data_type='hexdns_szonerecord', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='srvrecord',
            name='id',
            field=as207960_utils.models.TypedUUIDField(data_type='hexdns_zonesrvrecord', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='sshfprecord',
            name='id',
            field=as207960_utils.models.TypedUUIDField(data_type='hexdns_zonesshfprecord', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='txtrecord',
            name='id',
            field=as207960_utils.models.TypedUUIDField(data_type='hexdns_zonetxtrecord', primary_key=True, serialize=False),
        ),
        migrations.AddIndex(
            model_name='anamerecord',
            index=models.Index(fields=['record_name', 'zone'], name='dns_grpc_an_record__5ccb6f_idx'),
        ),
        migrations.AddIndex(
            model_name='caarecord',
            index=models.Index(fields=['record_name', 'zone'], name='dns_grpc_ca_record__9643d5_idx'),
        ),
        migrations.AddIndex(
            model_name='cnamerecord',
            index=models.Index(fields=['record_name', 'zone'], name='dns_grpc_cn_record__f5504e_idx'),
        ),
        migrations.AddIndex(
            model_name='dsrecord',
            index=models.Index(fields=['record_name', 'zone'], name='dns_grpc_ds_record__9da5be_idx'),
        ),
        migrations.AddIndex(
            model_name='hinforecord',
            index=models.Index(fields=['record_name', 'zone'], name='dns_grpc_hi_record__18a0ad_idx'),
        ),
        migrations.AddIndex(
            model_name='locrecord',
            index=models.Index(fields=['record_name', 'zone'], name='dns_grpc_lo_record__30d955_idx'),
        ),
        migrations.AddIndex(
            model_name='mxrecord',
            index=models.Index(fields=['record_name', 'zone'], name='dns_grpc_mx_record__7ff6a7_idx'),
        ),
        migrations.AddIndex(
            model_name='naptrrecord',
            index=models.Index(fields=['record_name', 'zone'], name='dns_grpc_na_record__049650_idx'),
        ),
        migrations.AddIndex(
            model_name='nsrecord',
            index=models.Index(fields=['record_name', 'zone'], name='dns_grpc_ns_record__222ed0_idx'),
        ),
        migrations.AddIndex(
            model_name='ptrrecord',
            index=models.Index(fields=['record_address', 'zone'], name='dns_grpc_pt_record__3b0725_idx'),
        ),
        migrations.AddIndex(
            model_name='reversensrecord',
            index=models.Index(fields=['record_address', 'zone'], name='dns_grpc_re_record__7008f0_idx'),
        ),
        migrations.AddIndex(
            model_name='rprecord',
            index=models.Index(fields=['record_name', 'zone'], name='dns_grpc_rp_record__f0da2e_idx'),
        ),
        migrations.AddIndex(
            model_name='srvrecord',
            index=models.Index(fields=['record_name', 'zone'], name='dns_grpc_sr_record__9e774f_idx'),
        ),
        migrations.AddIndex(
            model_name='sshfprecord',
            index=models.Index(fields=['record_name', 'zone'], name='dns_grpc_ss_record__60fc0a_idx'),
        ),
        migrations.AddIndex(
            model_name='txtrecord',
            index=models.Index(fields=['record_name', 'zone'], name='dns_grpc_tx_record__8ef4d2_idx'),
        ),
        migrations.AddField(
            model_name='dnszoneupdatesecrets',
            name='zone',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dns_grpc.dnszone'),
        ),
    ]
