# Generated by Django 3.1.3 on 2020-11-26 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dns_grpc', '0003_auto_20200910_2109'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='subscription_active',
            field=models.BooleanField(blank=True, default=False),
            preserve_default=False,
        ),
    ]
