# Generated by Django 3.0.5 on 2020-05-10 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dns_grpc", "0003_dsrecord"),
    ]

    operations = [
        migrations.AddField(
            model_name="dnszone",
            name="zsk_private",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="dsrecord",
            name="algorithm",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (5, "RSA/SHA-1 (5) INSECURE"),
                    (7, "RSASHA1-NSEC3-SHA1 (7) INSECURE"),
                    (8, "RSA/SHA-256 (8)"),
                    (10, "RSA/SHA-512 (10)"),
                    (13, "ECDSA Curve P-256 with SHA-256 (13)"),
                    (14, "ECDSA Curve P-384 with SHA-384 (14)"),
                    (15, "Ed25519 (15)"),
                    (16, "Ed448 (16)"),
                ]
            ),
        ),
    ]
