# Generated by Django 3.1.3 on 2020-11-26 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dns_grpc', '0004_account_subscription_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='subscription_active',
            field=models.BooleanField(default=False),
        ),
    ]
