# Generated by Django 3.0.5 on 2020-05-11 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dns_grpc", "0004_auto_20200510_1300"),
    ]

    operations = [
        migrations.AddField(
            model_name="reversednszone",
            name="zsk_private",
            field=models.TextField(blank=True, null=True),
        ),
    ]
