# Generated by Django 3.0.4 on 2020-03-31 10:59

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("dns_grpc", "0004_auto_20200329_2006"),
    ]

    operations = [
        migrations.CreateModel(
            name="SRVRecord",
            fields=[
                (
                    "dnszonerecord_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="dns_grpc.DNSZoneRecord",
                    ),
                ),
                (
                    "priority",
                    models.PositiveIntegerField(
                        validators=[django.core.validators.MaxValueValidator(65535)]
                    ),
                ),
                (
                    "weight",
                    models.PositiveIntegerField(
                        validators=[django.core.validators.MaxValueValidator(65535)]
                    ),
                ),
                (
                    "port",
                    models.PositiveIntegerField(
                        validators=[django.core.validators.MaxValueValidator(65535)]
                    ),
                ),
                ("target", models.CharField(max_length=255)),
            ],
            options={
                "verbose_name": "SRV record",
                "verbose_name_plural": "SRV records",
            },
            bases=("dns_grpc.dnszonerecord",),
        ),
        migrations.CreateModel(
            name="TXTRecord",
            fields=[
                (
                    "dnszonerecord_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="dns_grpc.DNSZoneRecord",
                    ),
                ),
                ("data", models.TextField()),
            ],
            options={
                "verbose_name": "TXT record",
                "verbose_name_plural": "TXT records",
            },
            bases=("dns_grpc.dnszonerecord",),
        ),
        migrations.AlterField(
            model_name="mxrecord",
            name="priority",
            field=models.PositiveIntegerField(
                validators=[django.core.validators.MaxValueValidator(65535)]
            ),
        ),
    ]
