# Generated by Django 3.0.4 on 2020-03-31 11:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("dns_grpc", "0005_auto_20200331_1059"),
    ]

    operations = [
        migrations.CreateModel(
            name="PTRRecord",
            fields=[
                (
                    "reversednszonerecord_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="dns_grpc.ReverseDNSZoneRecord",
                    ),
                ),
                ("pointer", models.CharField(max_length=255)),
            ],
            options={
                "verbose_name": "PTR record",
                "verbose_name_plural": "PTR records",
            },
            bases=("dns_grpc.reversednszonerecord",),
        ),
    ]
