# Generated by Django 3.1.4 on 2020-12-10 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dns_grpc', '0005_auto_20201126_2120'),
    ]

    operations = [
        migrations.AddField(
            model_name='dnszone',
            name='num_check_fails',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
