# Generated by Django 3.1.4 on 2021-01-24 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dns_grpc', '0006_dnszone_num_check_fails'),
    ]

    operations = [
        migrations.AddField(
            model_name='reversednszone',
            name='num_check_fails',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='secondarydnszone',
            name='num_check_fails',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
