# Generated by Django 3.0.5 on 2020-05-21 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dns_grpc', '0007_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='dnszone',
            name='active',
            field=models.BooleanField(blank=True, default=True),
        ),
        migrations.AddField(
            model_name='dnszone',
            name='charged',
            field=models.BooleanField(blank=True, default=True),
        ),
        migrations.AddField(
            model_name='reversednszone',
            name='active',
            field=models.BooleanField(blank=True, default=True),
        ),
        migrations.AddField(
            model_name='reversednszone',
            name='charged',
            field=models.BooleanField(blank=True, default=True),
        ),
        migrations.AlterField(
            model_name='addressrecord',
            name='ttl',
            field=models.PositiveIntegerField(default=3600, verbose_name='Time to Live (seconds)'),
        ),
        migrations.AlterField(
            model_name='caarecord',
            name='ttl',
            field=models.PositiveIntegerField(default=3600, verbose_name='Time to Live (seconds)'),
        ),
        migrations.AlterField(
            model_name='cnamerecord',
            name='ttl',
            field=models.PositiveIntegerField(default=3600, verbose_name='Time to Live (seconds)'),
        ),
        migrations.AlterField(
            model_name='dsrecord',
            name='ttl',
            field=models.PositiveIntegerField(default=3600, verbose_name='Time to Live (seconds)'),
        ),
        migrations.AlterField(
            model_name='dynamicaddressrecord',
            name='ttl',
            field=models.PositiveIntegerField(default=3600, verbose_name='Time to Live (seconds)'),
        ),
        migrations.AlterField(
            model_name='mxrecord',
            name='ttl',
            field=models.PositiveIntegerField(default=3600, verbose_name='Time to Live (seconds)'),
        ),
        migrations.AlterField(
            model_name='naptrrecord',
            name='ttl',
            field=models.PositiveIntegerField(default=3600, verbose_name='Time to Live (seconds)'),
        ),
        migrations.AlterField(
            model_name='nsrecord',
            name='ttl',
            field=models.PositiveIntegerField(default=3600, verbose_name='Time to Live (seconds)'),
        ),
        migrations.AlterField(
            model_name='srvrecord',
            name='ttl',
            field=models.PositiveIntegerField(default=3600, verbose_name='Time to Live (seconds)'),
        ),
        migrations.AlterField(
            model_name='sshfprecord',
            name='ttl',
            field=models.PositiveIntegerField(default=3600, verbose_name='Time to Live (seconds)'),
        ),
        migrations.AlterField(
            model_name='txtrecord',
            name='ttl',
            field=models.PositiveIntegerField(default=3600, verbose_name='Time to Live (seconds)'),
        ),
    ]
