# Generated by Django 2.2.18 on 2021-03-09 12:22

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import dns_grpc.models
import as207960_utils.models


class Migration(migrations.Migration):

    dependencies = [
        ('dns_grpc', '0007_auto_20210124_1452'),
    ]

    operations = [
        migrations.AddField(
            model_name='dnszone',
            name='cds_disable',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.CreateModel(
            name='DNSZoneAdditionalCDS',
            fields=[
                ('id', as207960_utils.models.TypedUUIDField(data_type='hexdns_zoneadditionalcds', primary_key=True, serialize=False)),
                ('key_tag', models.SmallIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(65535)])),
                ('algorithm', models.SmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(255)])),
                ('digest_type', models.SmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(255)])),
                ('digest', models.TextField(validators=[dns_grpc.models.hex_validator])),
                ('dns_zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dns_grpc.DNSZone')),
            ],
        ),
        migrations.CreateModel(
            name='DNSZoneAdditionalCDNSKEY',
            fields=[
                ('id', as207960_utils.models.TypedUUIDField(data_type='hexdns_zoneadditionalcdnskey', primary_key=True, serialize=False)),
                ('flags', models.SmallIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(65535)])),
                ('protocol', models.SmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(255)])),
                ('algorithm', models.SmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(255)])),
                ('public_key', models.TextField(validators=[dns_grpc.models.b64_validator])),
                ('dns_zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dns_grpc.DNSZone')),
            ],
        ),
    ]
