# Generated by Django 3.0.5 on 2020-05-21 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dns_grpc', '0008_auto_20200521_0917'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dnszone',
            name='active',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
