# Generated by Django 2.2.18 on 2021-03-09 12:34

import as207960_utils.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dns_grpc', '0008_auto_20210309_1222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dnszoneadditionalcdnskey',
            name='id',
            field=as207960_utils.models.TypedUUIDField(data_type='hexdns_zoneadditionalcdnskey', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='dnszoneadditionalcds',
            name='id',
            field=as207960_utils.models.TypedUUIDField(data_type='hexdns_zoneadditionalcds', primary_key=True, serialize=False),
        ),
    ]
