# Generated by Django 2.2.18 on 2021-03-09 15:08

import as207960_utils.models
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import dns_grpc.models


class Migration(migrations.Migration):

    dependencies = [
        ('dns_grpc', '0008_auto_20210309_1222'),
    ]

    operations = [
        migrations.AddField(
            model_name='reversednszone',
            name='cds_disable',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='secondarydnszone',
            name='cds_disable',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='dnszoneadditionalcdnskey',
            name='dns_zone',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='additional_cdnskey', to='dns_grpc.DNSZone'),
        ),
        migrations.AlterField(
            model_name='dnszoneadditionalcds',
            name='dns_zone',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='additional_cds', to='dns_grpc.DNSZone'),
        ),
        migrations.CreateModel(
            name='ReverseDNSZoneAdditionalCDS',
            fields=[
                ('id', as207960_utils.models.TypedUUIDField(data_type='hexdns_rzoneadditionalcds', primary_key=True, serialize=False)),
                ('key_tag', models.SmallIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(65535)])),
                ('algorithm', models.SmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(255)])),
                ('digest_type', models.SmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(255)])),
                ('digest', models.TextField(validators=[dns_grpc.models.hex_validator])),
                ('dns_zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='additional_cds', to='dns_grpc.ReverseDNSZone')),
            ],
        ),
        migrations.CreateModel(
            name='ReverseDNSZoneAdditionalCDNSKEY',
            fields=[
                ('id', as207960_utils.models.TypedUUIDField(data_type='hexdns_rzoneadditionalcdnskey', primary_key=True, serialize=False)),
                ('flags', models.SmallIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(65535)])),
                ('protocol', models.SmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(255)])),
                ('algorithm', models.SmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(255)])),
                ('public_key', models.TextField(validators=[dns_grpc.models.b64_validator])),
                ('dns_zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='additional_cdnskey', to='dns_grpc.ReverseDNSZone')),
            ],
        ),
    ]
