# Generated by Django 3.0.5 on 2020-06-19 20:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dns_grpc', '0009_auto_20200521_1040'),
    ]

    operations = [
        migrations.CreateModel(
            name='SecondaryDNSZone',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('zone_root', models.CharField(max_length=255)),
                ('serial', models.PositiveIntegerField(null=True)),
                ('charged', models.BooleanField(blank=True, default=True)),
                ('active', models.BooleanField(blank=True, default=False)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Secondary DNS Zone',
                'verbose_name_plural': 'Secondary DNS Zones',
            },
        ),
    ]
