# Generated by Django 2.2.18 on 2021-04-14 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dns_grpc', '0010_githubinstallation_githubstate'),
    ]

    operations = [
        migrations.AddField(
            model_name='githubinstallation',
            name='user_access_token',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='githubinstallation',
            name='user_access_token_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='githubinstallation',
            name='user_refresh_token',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='githubinstallation',
            name='user_refresh_token_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='githubstate',
            name='redirect_uri',
            field=models.TextField(blank=True, null=True),
        ),
    ]
