# Generated by Django 3.1.8 on 2021-04-15 11:23

import as207960_utils.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dns_grpc', '0011_auto_20210414_2108'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='githubinstallation',
            options={'verbose_name': 'GitHub installation'},
        ),
        migrations.AlterModelOptions(
            name='githubstate',
            options={'verbose_name': 'GitHub state'},
        ),
        migrations.CreateModel(
            name='GitHubPagesRecord',
            fields=[
                ('record_name', models.CharField(default='@', max_length=255, verbose_name='Record name (@ for zone root)')),
                ('ttl', models.PositiveIntegerField(default=3600, verbose_name='Time to Live (seconds)')),
                ('id', as207960_utils.models.TypedUUIDField(data_type='hexdns_githubpagesrecord', primary_key=True, serialize=False)),
                ('repo_owner', models.CharField(blank=True, max_length=255, null=True)),
                ('repo_name', models.CharField(blank=True, max_length=255, null=True)),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dns_grpc.dnszone')),
            ],
            options={
                'verbose_name': 'GitHub Pages record',
                'verbose_name_plural': 'GitHub Pages records',
            },
        ),
        migrations.AddIndex(
            model_name='githubpagesrecord',
            index=models.Index(fields=['record_name', 'zone'], name='dns_grpc_gi_record__9be530_idx'),
        ),
    ]
