# Generated by Django 3.0.7 on 2020-06-19 21:16

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('dns_grpc', '0011_secondarydnszone_primary'),
    ]

    operations = [
        migrations.CreateModel(
            name='SecondaryDNSZoneRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('record_name', models.CharField(max_length=255)),
                ('ttl', models.PositiveIntegerField(verbose_name='Time to Live (seconds)')),
                ('rtype', models.PositiveSmallIntegerField()),
                ('rdata', models.BinaryField()),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dns_grpc.SecondaryDNSZone')),
            ],
            options={
                'verbose_name': 'Secondary DNS Zone Record',
                'verbose_name_plural': 'Secondary DNS Zones Record',
            },
        ),
    ]
