# Generated by Django 3.0.7 on 2020-06-26 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dns_grpc', '0012_secondarydnszonerecord'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='secondarydnszonerecord',
            options={'ordering': ('record_name', 'rtype'), 'verbose_name': 'Secondary DNS Zone Record', 'verbose_name_plural': 'Secondary DNS Zones Record'},
        ),
        migrations.AddField(
            model_name='secondarydnszone',
            name='error',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='ptrrecord',
            name='ttl',
            field=models.PositiveIntegerField(default=3600, verbose_name='Time to Live (seconds)'),
        ),
    ]
