# Generated by Django 3.0.7 on 2020-06-28 12:37

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('dns_grpc', '0013_auto_20200626_1006'),
    ]

    operations = [
        migrations.CreateModel(
            name='ANAMERecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('record_name', models.CharField(default='@', max_length=255, verbose_name='Record name (@ for zone root)')),
                ('ttl', models.PositiveIntegerField(default=3600, verbose_name='Time to Live (seconds)')),
                ('alias', models.CharField(max_length=255)),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dns_grpc.DNSZone')),
            ],
            options={
                'verbose_name': 'ANAME record',
                'verbose_name_plural': 'ANAME records',
            },
        ),
    ]
