# Generated by Django 3.1.12 on 2021-06-14 21:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dns_grpc', '0013_auto_20210614_2108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='httpsrecord',
            name='target_port',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(65535)]),
        ),
    ]
