# Generated by Django 3.0.7 on 2020-07-13 09:45

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('dns_grpc', '0014_anamerecord'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReverseNSRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('record_address', models.GenericIPAddressField()),
                ('ttl', models.PositiveIntegerField(default=3600, verbose_name='Time to Live (seconds)')),
                ('record_prefix', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(128)])),
                ('nameserver', models.CharField(max_length=255, verbose_name='Name server')),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dns_grpc.ReverseDNSZone')),
            ],
            options={
                'verbose_name': 'NS record',
                'verbose_name_plural': 'NS records',
            },
        ),
    ]
