# Generated by Django 3.1.12 on 2021-06-20 15:49

import as207960_utils.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dns_grpc', '0015_googleinstallation_googlestate'),
    ]

    operations = [
        migrations.CreateModel(
            name='RedirectRecord',
            fields=[
                ('record_name', models.CharField(default='@', max_length=255, verbose_name='Record name (@ for zone root)')),
                ('ttl', models.PositiveIntegerField(default=3600, verbose_name='Time to Live (seconds)')),
                ('id', as207960_utils.models.TypedUUIDField(data_type='hexdns_zoneredirectrecord', primary_key=True, serialize=False)),
                ('target', models.URLField()),
                ('include_path', models.BooleanField(blank=True)),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dns_grpc.dnszone')),
            ],
            options={
                'verbose_name': 'Redirect record',
                'verbose_name_plural': 'Redirect records',
                'ordering': ['record_name'],
                'abstract': False,
            },
        ),
        migrations.AddIndex(
            model_name='redirectrecord',
            index=models.Index(fields=['record_name', 'zone'], name='dns_grpc_re_record__b6ce3b_idx'),
        ),
    ]
