# Generated by Django 3.1.12 on 2021-07-19 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dns_grpc', '0016_auto_20210620_1549'),
    ]

    operations = [
        migrations.AddField(
            model_name='dnszoneupdatesecrets',
            name='restrict_to',
            field=models.CharField(default='@', max_length=255, verbose_name='Restrict to (@ for zone root)'),
        ),
    ]
