# Generated by Django 3.1.12 on 2022-01-28 13:28

import as207960_utils.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dns_grpc', '0017_dnszoneupdatesecrets_restrict_to'),
    ]

    operations = [
        migrations.CreateModel(
            name='DNSZoneCustomNS',
            fields=[
                ('id', as207960_utils.models.TypedUUIDField(data_type='hexdns_zonecustomns', primary_key=True, serialize=False)),
                ('nameserver', models.CharField(max_length=255, verbose_name='Name server')),
                ('dns_zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_ns', to='dns_grpc.dnszone')),
            ],
        ),
    ]
