# Generated by Django 3.0.7 on 2020-07-25 20:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dns_grpc', '0017_auto_20200725_1446'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dnszone',
            name='user',
        ),
        migrations.RemoveField(
            model_name='reversednszone',
            name='user',
        ),
        migrations.RemoveField(
            model_name='secondarydnszone',
            name='user',
        ),
    ]
