# Generated by Django 3.1.12 on 2022-05-27 11:18

import as207960_utils.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dns_grpc', '0018_dnszonecustomns'),
    ]

    operations = [
        migrations.CreateModel(
            name='DHCIDRecord',
            fields=[
                ('record_name', models.CharField(default='@', max_length=255, verbose_name='Record name (@ for zone root)')),
                ('ttl', models.PositiveIntegerField(default=3600, verbose_name='Time to Live (seconds)')),
                ('id', as207960_utils.models.TypedUUIDField(data_type='hexdns_zonedhcidrecord', primary_key=True, serialize=False)),
                ('data', models.BinaryField()),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dns_grpc.dnszone')),
            ],
            options={
                'verbose_name': 'DHCID record',
                'verbose_name_plural': 'DHCID records',
                'ordering': ['record_name'],
                'abstract': False,
            },
        ),
        migrations.AddIndex(
            model_name='dhcidrecord',
            index=models.Index(fields=['record_name', 'zone'], name='dns_grpc_dh_record__3f60b9_idx'),
        ),
    ]
