# Generated by Django 3.1.12 on 2022-05-27 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dns_grpc', '0019_auto_20220527_1118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addressrecord',
            name='auto_reverse',
            field=models.BooleanField(default=True, verbose_name='Automatically serve reverse PTR records'),
        ),
    ]
