# Generated by Django 3.1.14 on 2022-07-29 10:59

from django.db import migrations, models
import dns_grpc.models


class Migration(migrations.Migration):

    dependencies = [
        ('dns_grpc', '0021_reversednszonecustomns'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dsrecord',
            name='digest',
            field=models.TextField(validators=[dns_grpc.models.hex_validator]),
        ),
        migrations.AlterField(
            model_name='naptrrecord',
            name='regexp',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
