# Generated by Django 3.1.14 on 2022-10-25 15:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dns_grpc', '0022_auto_20220729_1059'),
    ]

    operations = [
        migrations.CreateModel(
            name='ANAMERecordCache',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.GenericIPAddressField(verbose_name='Address (IPv4/IPv6)')),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cached', to='dns_grpc.anamerecord')),
            ],
        ),
    ]
