# Generated by Django 3.1.14 on 2023-01-09 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dns_grpc', '0023_anamerecordcache'),
    ]

    operations = [
        migrations.AddField(
            model_name='secondarydnszone',
            name='error_message',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
