# Generated by Django 3.1.14 on 2023-02-04 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dns_grpc', '0024_secondarydnszone_error_message'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='secondarydnszonerecord',
            options={'verbose_name': 'Secondary DNS Zone Record', 'verbose_name_plural': 'Secondary DNS Zones Record'},
        ),
        migrations.RemoveIndex(
            model_name='secondarydnszonerecord',
            name='dns_grpc_se_record__d5b143_idx',
        ),
        migrations.RemoveField(
            model_name='secondarydnszonerecord',
            name='rdata',
        ),
        migrations.RemoveField(
            model_name='secondarydnszonerecord',
            name='record_name',
        ),
        migrations.RemoveField(
            model_name='secondarydnszonerecord',
            name='rtype',
        ),
        migrations.RemoveField(
            model_name='secondarydnszonerecord',
            name='ttl',
        ),
        migrations.AddField(
            model_name='secondarydnszonerecord',
            name='record_text',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
