# Generated by Django 3.1.14 on 2023-06-16 08:55

import as207960_utils.models
from django.db import migrations, models
import django.db.models.deletion
import dns_grpc.models


class Migration(migrations.Migration):

    dependencies = [
        ('dns_grpc', '0025_auto_20230204_1609'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReverseDNSZoneAXFRSecrets',
            fields=[
                ('id', as207960_utils.models.TypedUUIDField(data_type='hexdns_rzoneaxfrsecret', primary_key=True, serialize=False)),
                ('secret', models.BinaryField(default=dns_grpc.models.make_update_secret)),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dns_grpc.reversednszone')),
            ],
        ),
        migrations.CreateModel(
            name='DNSZoneAXFRSecrets',
            fields=[
                ('id', as207960_utils.models.TypedUUIDField(data_type='hexdns_zoneaxfrsecret', primary_key=True, serialize=False)),
                ('secret', models.BinaryField(default=dns_grpc.models.make_update_secret)),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dns_grpc.dnszone')),
            ],
        ),
    ]
