# Generated by Django 3.1.14 on 2023-06-16 09:06

import as207960_utils.models
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dns_grpc', '0026_dnszoneaxfrsecrets_reversednszoneaxfrsecrets'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReverseDNSZoneAXFRNotify',
            fields=[
                ('id', as207960_utils.models.TypedUUIDField(data_type='hexdns_rzoneaxfrnotify', primary_key=True, serialize=False)),
                ('server', models.CharField(max_length=255)),
                ('port', models.PositiveSmallIntegerField(default=53, validators=[django.core.validators.MaxValueValidator(65535)])),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dns_grpc.reversednszone')),
            ],
        ),
        migrations.CreateModel(
            name='ReverseDNSZoneAXFRIPACL',
            fields=[
                ('id', as207960_utils.models.TypedUUIDField(data_type='hexdns_rzoneaxfripacl', primary_key=True, serialize=False)),
                ('address', models.GenericIPAddressField(db_index=True)),
                ('prefix', models.PositiveIntegerField(db_index=True, validators=[django.core.validators.MaxValueValidator(128)])),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dns_grpc.reversednszone')),
            ],
        ),
        migrations.CreateModel(
            name='DNSZoneAXFRNotify',
            fields=[
                ('id', as207960_utils.models.TypedUUIDField(data_type='hexdns_zoneaxfrnotify', primary_key=True, serialize=False)),
                ('server', models.CharField(max_length=255)),
                ('port', models.PositiveSmallIntegerField(default=53, validators=[django.core.validators.MaxValueValidator(65535)])),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dns_grpc.dnszone')),
            ],
        ),
        migrations.CreateModel(
            name='DNSZoneAXFRIPACL',
            fields=[
                ('id', as207960_utils.models.TypedUUIDField(data_type='hexdns_zoneaxfripacl', primary_key=True, serialize=False)),
                ('address', models.GenericIPAddressField(db_index=True)),
                ('prefix', models.PositiveIntegerField(db_index=True, validators=[django.core.validators.MaxValueValidator(128)])),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dns_grpc.dnszone')),
            ],
        ),
    ]
