# Generated by Django 4.2.5 on 2023-09-19 13:13

import as207960_utils.models
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import dns_grpc.models


class Migration(migrations.Migration):
    dependencies = [
        ("dns_grpc", "0028_auto_20230616_0938"),
    ]

    operations = [
        migrations.CreateModel(
            name="DNSKEYRecord",
            fields=[
                (
                    "record_name",
                    models.CharField(
                        default="@",
                        max_length=255,
                        verbose_name="Record name (@ for zone root)",
                    ),
                ),
                (
                    "ttl",
                    models.PositiveIntegerField(
                        default=3600, verbose_name="Time to Live (seconds)"
                    ),
                ),
                (
                    "id",
                    as207960_utils.models.TypedUUIDField(
                        data_type="hexdns_zonednskeyrecord",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "flags",
                    models.PositiveSmallIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(65535),
                        ]
                    ),
                ),
                (
                    "protocol",
                    models.PositiveSmallIntegerField(
                        default=3,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(255),
                        ],
                    ),
                ),
                (
                    "algorithm",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (5, "RSA/SHA-1 (5) INSECURE"),
                            (7, "RSASHA1-NSEC3-SHA1 (7) INSECURE"),
                            (8, "RSA/SHA-256 (8)"),
                            (10, "RSA/SHA-512 (10)"),
                            (13, "ECDSA Curve P-256 with SHA-256 (13)"),
                            (14, "ECDSA Curve P-384 with SHA-384 (14)"),
                            (15, "Ed25519 (15)"),
                            (16, "Ed448 (16)"),
                        ]
                    ),
                ),
                (
                    "public_key",
                    models.TextField(validators=[dns_grpc.models.b64_validator]),
                ),
                (
                    "zone",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="dns_grpc.dnszone",
                    ),
                ),
            ],
            options={
                "verbose_name": "DNSKEY record",
                "verbose_name_plural": "DNSKEY records",
                "ordering": ["record_name"],
                "abstract": False,
                "indexes": [
                    models.Index(
                        fields=["record_name", "zone"],
                        name="dns_grpc_dn_record__7d05a4_idx",
                    )
                ],
            },
        ),
    ]
