# Generated by Django 4.2.7 on 2023-11-14 20:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dns_grpc", "0029_dnskeyrecord"),
    ]

    operations = [
        migrations.AlterField(
            model_name="addressrecord",
            name="record_name",
            field=models.CharField(
                db_index=True,
                default="@",
                max_length=255,
                verbose_name="Record name (@ for zone root)",
            ),
        ),
        migrations.AlterField(
            model_name="anamerecord",
            name="record_name",
            field=models.CharField(
                db_index=True,
                default="@",
                max_length=255,
                verbose_name="Record name (@ for zone root)",
            ),
        ),
        migrations.AlterField(
            model_name="caarecord",
            name="record_name",
            field=models.CharField(
                db_index=True,
                default="@",
                max_length=255,
                verbose_name="Record name (@ for zone root)",
            ),
        ),
        migrations.AlterField(
            model_name="cnamerecord",
            name="record_name",
            field=models.CharField(
                db_index=True,
                default="@",
                max_length=255,
                verbose_name="Record name (@ for zone root)",
            ),
        ),
        migrations.AlterField(
            model_name="dhcidrecord",
            name="record_name",
            field=models.CharField(
                db_index=True,
                default="@",
                max_length=255,
                verbose_name="Record name (@ for zone root)",
            ),
        ),
        migrations.AlterField(
            model_name="dnskeyrecord",
            name="record_name",
            field=models.CharField(
                db_index=True,
                default="@",
                max_length=255,
                verbose_name="Record name (@ for zone root)",
            ),
        ),
        migrations.AlterField(
            model_name="dsrecord",
            name="record_name",
            field=models.CharField(
                db_index=True,
                default="@",
                max_length=255,
                verbose_name="Record name (@ for zone root)",
            ),
        ),
        migrations.AlterField(
            model_name="dynamicaddressrecord",
            name="record_name",
            field=models.CharField(
                db_index=True,
                default="@",
                max_length=255,
                verbose_name="Record name (@ for zone root)",
            ),
        ),
        migrations.AlterField(
            model_name="githubpagesrecord",
            name="record_name",
            field=models.CharField(
                db_index=True,
                default="@",
                max_length=255,
                verbose_name="Record name (@ for zone root)",
            ),
        ),
        migrations.AlterField(
            model_name="hinforecord",
            name="record_name",
            field=models.CharField(
                db_index=True,
                default="@",
                max_length=255,
                verbose_name="Record name (@ for zone root)",
            ),
        ),
        migrations.AlterField(
            model_name="httpsrecord",
            name="record_name",
            field=models.CharField(
                db_index=True,
                default="@",
                max_length=255,
                verbose_name="Record name (@ for zone root)",
            ),
        ),
        migrations.AlterField(
            model_name="locrecord",
            name="record_name",
            field=models.CharField(
                db_index=True,
                default="@",
                max_length=255,
                verbose_name="Record name (@ for zone root)",
            ),
        ),
        migrations.AlterField(
            model_name="mxrecord",
            name="record_name",
            field=models.CharField(
                db_index=True,
                default="@",
                max_length=255,
                verbose_name="Record name (@ for zone root)",
            ),
        ),
        migrations.AlterField(
            model_name="naptrrecord",
            name="record_name",
            field=models.CharField(
                db_index=True,
                default="@",
                max_length=255,
                verbose_name="Record name (@ for zone root)",
            ),
        ),
        migrations.AlterField(
            model_name="nsrecord",
            name="record_name",
            field=models.CharField(
                db_index=True,
                default="@",
                max_length=255,
                verbose_name="Record name (@ for zone root)",
            ),
        ),
        migrations.AlterField(
            model_name="ptrrecord",
            name="record_address",
            field=models.GenericIPAddressField(db_index=True),
        ),
        migrations.AlterField(
            model_name="redirectrecord",
            name="record_name",
            field=models.CharField(
                db_index=True,
                default="@",
                max_length=255,
                verbose_name="Record name (@ for zone root)",
            ),
        ),
        migrations.AlterField(
            model_name="reversensrecord",
            name="record_address",
            field=models.GenericIPAddressField(db_index=True),
        ),
        migrations.AlterField(
            model_name="rprecord",
            name="record_name",
            field=models.CharField(
                db_index=True,
                default="@",
                max_length=255,
                verbose_name="Record name (@ for zone root)",
            ),
        ),
        migrations.AlterField(
            model_name="srvrecord",
            name="record_name",
            field=models.CharField(
                db_index=True,
                default="@",
                max_length=255,
                verbose_name="Record name (@ for zone root)",
            ),
        ),
        migrations.AlterField(
            model_name="sshfprecord",
            name="record_name",
            field=models.CharField(
                db_index=True,
                default="@",
                max_length=255,
                verbose_name="Record name (@ for zone root)",
            ),
        ),
        migrations.AlterField(
            model_name="txtrecord",
            name="record_name",
            field=models.CharField(
                db_index=True,
                default="@",
                max_length=255,
                verbose_name="Record name (@ for zone root)",
            ),
        ),
    ]
