# Generated by Django 4.2.7 on 2023-11-14 23:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dns_grpc", "0030_alter_addressrecord_record_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="dnszone",
            name="last_resign",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="reversednszone",
            name="last_resign",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
