# Generated by Django 4.2.7 on 2024-01-15 20:42

import as207960_utils.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("dns_grpc", "0031_dnszone_last_resign_reversednszone_last_resign"),
    ]

    operations = [
        migrations.CreateModel(
            name="TLSARecord",
            fields=[
                (
                    "record_name",
                    models.CharField(
                        db_index=True,
                        default="@",
                        max_length=255,
                        verbose_name="Record name (@ for zone root)",
                    ),
                ),
                (
                    "ttl",
                    models.PositiveIntegerField(
                        default=3600, verbose_name="Time to Live (seconds)"
                    ),
                ),
                (
                    "id",
                    as207960_utils.models.TypedUUIDField(
                        data_type="hexdns_zonetlsarecord",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "certificate_usage",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (0, "0 - CA constraint"),
                            (1, "1 - Service certificate constraint"),
                            (2, "2 - Trust anchor assertion"),
                            (3, "3 - Domain-issued certificate"),
                            (255, "255 - Private Use"),
                        ]
                    ),
                ),
                (
                    "selector",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (0, "0 - Full certificate"),
                            (1, "1 - SubjectPublicKeyInfo"),
                            (255, "255 - Private Use"),
                        ]
                    ),
                ),
                (
                    "matching_type",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (0, "0 - No hash used (full certificate)"),
                            (1, "1 - SHA256"),
                            (2, "2 - SHA512"),
                            (255, "255 - Private Use"),
                        ]
                    ),
                ),
                ("certificate_data", models.BinaryField()),
                (
                    "zone",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="dns_grpc.dnszone",
                    ),
                ),
            ],
            options={
                "verbose_name": "TLSA record",
                "verbose_name_plural": "TLSA records",
                "ordering": ["record_name"],
                "abstract": False,
                "indexes": [
                    models.Index(
                        fields=["record_name", "zone"],
                        name="dns_grpc_tl_record__f36ca2_idx",
                    )
                ],
            },
        ),
    ]
