# Generated by Django 4.2.7 on 2024-01-21 18:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("dns_grpc", "0032_tlsarecord"),
    ]

    operations = [
        migrations.AddField(
            model_name="githubpagesrecord",
            name="installation",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="dns_grpc.githubinstallation",
            ),
        ),
        migrations.AddIndex(
            model_name="githubpagesrecord",
            index=models.Index(
                fields=["installation"], name="dns_grpc_gi_install_9d3cd4_idx"
            ),
        ),
    ]
