# Generated by Django 5.0.7 on 2024-08-06 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dns_grpc", "0033_githubpagesrecord_installation_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="dynamicaddressrecord",
            name="last_modified",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
