# Generated by Django 5.0.7 on 2024-08-06 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dns_grpc", "0034_dynamicaddressrecord_last_modified"),
    ]

    operations = [
        migrations.AddField(
            model_name="dnszone",
            name="zsk_private_ed25519",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="reversednszone",
            name="zsk_private_ed25519",
            field=models.TextField(blank=True, null=True),
        ),
    ]
