# Generated by Django 5.0.9 on 2025-06-11 17:09

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dns_grpc', '0035_ed25519'),
    ]

    operations = [
        migrations.AddField(
            model_name='dnszone',
            name='soa_email_id',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
        ),
        migrations.AddField(
            model_name='reversednszone',
            name='soa_email_id',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
        ),
    ]
