# Generated by Django 5.0.9 on 2025-11-26 09:18

import as207960_utils.models
import django.core.validators
import django.db.models.deletion
import dns_grpc.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dns_grpc', '0036_dnszone_soa_email_id_reversednszone_soa_email_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReverseDSRecord',
            fields=[
                ('record_address', models.GenericIPAddressField(db_index=True)),
                ('ttl', models.PositiveIntegerField(default=3600, verbose_name='Time to Live (seconds)')),
                ('id', as207960_utils.models.TypedUUIDField(data_type='hexdns_rzonedsrecord', primary_key=True, serialize=False)),
                ('record_prefix', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(128)])),
                ('key_tag', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(65535)])),
                ('algorithm', models.PositiveSmallIntegerField(choices=[(5, 'RSA/SHA-1 (5) INSECURE'), (7, 'RSASHA1-NSEC3-SHA1 (7) INSECURE'), (8, 'RSA/SHA-256 (8)'), (10, 'RSA/SHA-512 (10)'), (13, 'ECDSA Curve P-256 with SHA-256 (13)'), (14, 'ECDSA Curve P-384 with SHA-384 (14)'), (15, 'Ed25519 (15)'), (16, 'Ed448 (16)')])),
                ('digest_type', models.PositiveSmallIntegerField(choices=[(1, 'SHA-1 (1) INSECURE'), (2, 'SHA-256 (2)'), (3, 'GOST R 34.11-94 (3)'), (4, 'SHA-384 (4)')])),
                ('digest', models.TextField(validators=[dns_grpc.models.hex_validator])),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dns_grpc.reversednszone')),
            ],
            options={
                'verbose_name': 'DS record',
                'verbose_name_plural': 'DS records',
                'ordering': ['record_address'],
                'abstract': False,
                'indexes': [models.Index(fields=['record_address', 'zone'], name='dns_grpc_re_record__9333d4_idx')],
            },
        ),
    ]
