# Generated by Django 5.0.9 on 2026-02-25 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dns_grpc', '0037_reversedsrecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='secondarydnszone',
            name='error_timestamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
