FROM python:3.8

RUN mkdir /app
WORKDIR /app
RUN pip install -U pip
RUN apt-get update && apt-get install -y knot && rm -rf /var/lib/apt/lists/*

RUN pip install -U prometheus-client

COPY knot_exporter /app
CMD ["python3", "/app/knot_exporter"]
