apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: hexdns-cache
  labels:
    app: hexdns
    part: cache
spec:
  selector:
    matchLabels:
      app: hexdns
      part: cache
  template:
    metadata:
      annotations:
        cni.projectcalico.org/ipv6pools: "[\"default-ipv6-ippool\"]"
      labels:
        app: hexdns
        part: cache
    spec:
      tolerations:
        - key: special
          operator: Equal
          value: edge
          effect: NoSchedule
      containers:
        - name: cache
          image: as207960/dns-cache:5
          args:
            - "-a"
            - "::"
            - "-u"
            - "http://hexdns-grpc:50051"
          imagePullPolicy: Always
          ports:
            - containerPort: 53
          env:
            - name: DNS_SERVER_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: RUST_LOG
              value: "info"
      terminationGracePeriodSeconds: 30
---
apiVersion: v1
kind: Service
metadata:
  name: hexdns-coredns-udp
  annotations:
    metallb.universe.tf/allow-shared-ip: "hexdns-coredns"
spec:
  type: LoadBalancer
  externalTrafficPolicy: Local
  selector:
    app: hexdns
    part: cache
  ports:
    - port: 53
      targetPort: 53
      protocol: UDP
      name: dns-udp
---
apiVersion: v1
kind: Service
metadata:
  name: hexdns-coredns-tcp
  annotations:
    metallb.universe.tf/allow-shared-ip: "hexdns-coredns"
spec:
  type: LoadBalancer
  externalTrafficPolicy: Local
  selector:
    app: hexdns
    part: cache
  ports:
    - port: 53
      targetPort: 53
      protocol: TCP
      name: dns-tcp
