apiVersion: crd.projectcalico.org/v1
kind: IPPool
metadata:
  name: hexdns-notify-ip6-ippool
spec:
  blockSize: 127
  cidr: 2001:678:fc8:2::10/125
  disabled: false
  nodeSelector: "!all()"
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: hexdns-knot-axfr
data:
  knot.conf: |
    server:
        identity: "HexDNS"
        listen: 0.0.0.0@53
        listen: ::@53
        nsid: (nsid)

    database:
        journal-db-mode: asynchronous

    log:
      - target: stdout
        any: info
    
    key:
      - id: secondary-xfr
        algorithm: hmac-sha256
        secret: (xfr-secret)
    
    remote:
      - id: primary
        address: (primary-address)
        key: secondary-xfr
      - id: notify-sidecar
        address: 127.0.0.1@5353

    acl:
      - id: notify
        address: 127.0.0.1
        action: notify

    template:
      - id: zone
        journal-content: none
        master: primary
        acl: notify
        notify: notify-sidecar

    zone:
      - domain: catalog.dns.as207960.ltd.uk.
        master: primary
        catalog-role: interpret
        catalog-template: zone
        acl: notify
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hexdns-axfr
  labels:
    app: hexdns
    part: axfr
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hexdns
      part: axfr
  template:
    metadata:
      annotations:
        cni.projectcalico.org/ipv6pools: "[\"default-ipv6-ippool\"]"
      labels:
        app: hexdns
        part: axfr
    spec:
      volumes:
        - name: knot
          emptyDir: {}
        - name: config
          configMap:
            name: hexdns-knot-axfr
        - name: rundir
          emptyDir: {}
        - name: pubkey
          configMap:
            name: hexdns-key-pub
        - name: domains-pubkey
          configMap:
            name: domains-jwt-pub
      containers:
        - name: knot
          image: as207960/knotd:7
          imagePullPolicy: Always
          command: [
            "sh", "-c",
            "cp /config-template/knot.conf /config/knot.conf &&
             sed -i \"s/(xfr-secret)/$XFR_SECRET/g\" /config/knot.conf &&
             sed -i \"s/(primary-address)/$HEXDNS_KNOT_PRIMARY_SERVICE_HOST/g\" /config/knot.conf &&
             sed -i \"s/(nsid)/$HOSTNAME/g\" /config/knot.conf &&
             sleep 15 &&
             while true; do rm /rundir/knot.pid; knotd; done"
          ]
          readinessProbe:
            tcpSocket:
              port: 53
            initialDelaySeconds: 15
            periodSeconds: 10
          volumeMounts:
            - mountPath: "/storage/"
              name: knot
            - mountPath: "/config-template/"
              name: config
            - mountPath: "/rundir/"
              name: rundir
          envFrom:
            - secretRef:
                name: hexdns-knot-xfr
        - name: reloader
          image: as207960/hexdns-knot-sidecar-secondary:(version)
          imagePullPolicy: Always
          command: ["python3", "/app/sidecar-secondary.py"]
          envFrom:
            - secretRef:
                name: hexdns-rpc
        - name: axfr
          image: as207960/hexdns-axfr:(version)
          imagePullPolicy: Always
          readinessProbe:
            tcpSocket:
              port: 5053
            initialDelaySeconds: 15
            periodSeconds: 10
          volumeMounts:
            - mountPath: "/storage/"
              name: knot
          env:
            - name: RUST_LOG
              value: "info"
            - name: DNS_PORT
              value: "5053"
            - name: DNS_ADDR
              value: "::"
            - name: DNS_ZONES
              value: "/storage"
            - name: DNS_UPSTREAM
              value: "http://hexdns-grpc:50051"
        - name: notify
          image: as207960/hexdns-django:(version)
          imagePullPolicy: Always
          command: [ "sh", "-c", "python3 manage.py run-axfr-notify" ]
          volumeMounts:
            - mountPath: "/pubkey/"
              name: pubkey
            - mountPath: "/domains-pubkey/"
              name: domains-pubkey
          envFrom:
            - configMapRef:
                name: hexdns-django-conf
            - secretRef:
                name: hexdns-db-creds
              prefix: "DB_"
            - secretRef:
                name: hexdns-django-secret
            - secretRef:
                name: hexdns-keycloak
              prefix: "KEYCLOAK_"
            - secretRef:
                name: hexdns-email
              prefix: "EMAIL_"
            - secretRef:
                name: hexdns-github
              prefix: "GITHUB_"
            - secretRef:
                name: hexdns-google
              prefix: "GOOGLE_"
            - secretRef:
                name: hexdns-netnod
              prefix: "NETNOD_"
            - secretRef:
                name: hexdns-rpc
            - secretRef:
                name: hexdns-s3
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: hexdns-axfr
spec:
  podSelector:
    matchLabels:
      app: hexdns
      part: axfr
  policyTypes:
    - Ingress
  ingress:
    - ports:
      - protocol: TCP
        port: 5053
      - protocol: UDP
        port: 5053
---
apiVersion: v1
kind: Service
metadata:
  name: hexdns-axfr-tcp
  annotations:
    metallb.universe.tf/allow-shared-ip: "hexdns-axfr"
    metallb.universe.tf/loadBalancerIPs: "2a0e:1cc1:1::1:1a"
spec:
  selector:
    app: hexdns
    part: axfr
  type: LoadBalancer
  externalTrafficPolicy: Local
  ports:
    - port: 53
      targetPort: 5053
      protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: hexdns-axfr-udp
  annotations:
    metallb.universe.tf/allow-shared-ip: "hexdns-axfr"
    metallb.universe.tf/loadBalancerIPs: "2a0e:1cc1:1::1:1a"
spec:
  selector:
    app: hexdns
    part: axfr
  type: LoadBalancer
  externalTrafficPolicy: Local
  ports:
    - port: 53
      targetPort: 5053
      protocol: UDP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hexdns-axfr-notify
  labels:
    app: hexdns
    part: axfr-notify
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hexdns
      part: axfr-notify
  template:
    metadata:
      annotations:
        cni.projectcalico.org/ipv6pools: "[\"hexdns-notify-ip6-ippool\"]"
      labels:
        app: hexdns
        part: axfr-notify
    spec:
      containers:
        - name: notify
          image: as207960/hexdns-axfr-notify:(version)
          imagePullPolicy: Always
          env:
            - name: "RUST_LOG"
              value: "info"
          envFrom:
            - secretRef:
                name: hexdns-rpc
        - name: clatd
          image: as207960/clatd
          command: [
            "/bin/bash", "-c",
            "/clatd/clatd clat-v6-addr=fd2e:ae7d:58e3:f6ab::1 v4-conncheck-enable=no 'script-up=ip6tables -t nat -A POSTROUTING -o eth0 -j MASQUERADE'"
          ]
          securityContext:
            privileged: true
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: hexdns-axfr-notify
spec:
  podSelector:
    matchLabels:
      app: hexdns
      part: axfr-notify
  policyTypes:
    - Ingress