apiVersion: v1
kind: Service
metadata:
  name: hexdns-coredns-udp
  annotations:
    metallb.universe.tf/allow-shared-ip: "hexdns-coredns"
    metallb.universe.tf/loadBalancerIPs: "2a0e:1cc1:1::1:1"
spec:
  type: LoadBalancer
  externalTrafficPolicy: Local
  selector:
    app: hexdns
    part: knot
    role: secondary
  ports:
    - port: 53
      targetPort: 53
      protocol: UDP
      name: dns-udp
    - port: 853
      targetPort: 853
      protocol: UDP
      name: dns-quic
---
apiVersion: v1
kind: Service
metadata:
  name: hexdns-coredns-tcp
  annotations:
    metallb.universe.tf/allow-shared-ip: "hexdns-coredns"
    metallb.universe.tf/loadBalancerIPs: "2a0e:1cc1:1::1:1"
spec:
  type: LoadBalancer
  externalTrafficPolicy: Local
  selector:
    app: hexdns
    part: knot
    role: secondary
  ports:
    - port: 53
      targetPort: 53
      protocol: TCP
      name: dns-tcp
    - port: 853
      targetPort: 853
      protocol: TCP
      name: dns-tls
---
apiVersion: v1
kind: Service
metadata:
  name: hexdns-coredns-udp-2
  annotations:
    metallb.universe.tf/allow-shared-ip: "hexdns-coredns-2"
    metallb.universe.tf/loadBalancerIPs: "2a0e:1cc1:1::1:e"
spec:
  type: LoadBalancer
  externalTrafficPolicy: Local
  selector:
    app: hexdns
    part: knot
    role: secondary
  ports:
    - port: 53
      targetPort: 53
      protocol: UDP
      name: dns-udp
    - port: 853
      targetPort: 853
      protocol: UDPk
      name: dns-quic
---
apiVersion: v1
kind: Service
metadata:
  name: hexdns-coredns-tcp-2
  annotations:
    metallb.universe.tf/allow-shared-ip: "hexdns-coredns-2"
    metallb.universe.tf/loadBalancerIPs: "2a0e:1cc1:1::1:e"
spec:
  type: LoadBalancer
  externalTrafficPolicy: Local
  selector:
    app: hexdns
    part: knot
    role: secondary
  ports:
    - port: 53
      targetPort: 53
      protocol: TCP
      name: dns-tcp
    - port: 853
      targetPort: 853
      protocol: TCP
      name: dns-tls
