apiVersion: crd.projectcalico.org/v1
kind: IPPool
metadata:
  name: hexdns-primary-ip6-ippool
spec:
  blockSize: 127
  cidr: 2001:678:fc8:2::18/126
  disabled: false
  nodeSelector: "!all()"
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: hexdns-knot
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: hexdns-knot
data:
  knot.conf: |
    server:
        identity: "HexDNS"
        listen: 0.0.0.0@53
        listen: ::@53
        background-workers: 1
        rundir: /rundir/

    database:
        journal-db-mode: robust

    log:
      - target: stdout
        any: info
    
    key:
      - id: secondary-xfr
        algorithm: hmac-sha256
        secret: (xfr-secret)
      - id: netnod-cyfyngedig-1.
        algorithm: hmac-sha512
        secret: (netnod-xfr-secret)
    
    acl:
      - id: secondary-xfr
        action: transfer
        key: secondary-xfr
      - id: netnod-xfr
        action: transfer
        key: netnod-cyfyngedig-1.
    
    remote:
      - id: unbound-no-dns64
        address: (unbound-no-dns64)@5053
      - id: notify-sidecar
        address: 127.0.0.1@5353
      - id: netnod-dist-1
        address: 2a01:3f0:0:27::24
        key: netnod-cyfyngedig-1.
      - id: netnod-dist-2
        address: 2a01:3f0:0:28::25
        key: netnod-cyfyngedig-1.
    
    submission:
      - id: zone
        parent: unbound-no-dns64
        check-interval: 15m

    policy:
      - id: zone
        signing-threads: 4
        algorithm: ecdsap256sha256
        ksk-shared: on
        dnskey-ttl: 86400
        reproducible-signing: on
        nsec3: on
        cds-cdnskey-publish: always
        zsk-lifetime: 30d
        ksk-submission: zone
        nsec3-iterations: 10
    
      - id: zone-cds-disable
        signing-threads: 4
        algorithm: ecdsap256sha256
        ksk-shared: on
        dnskey-ttl: 86400
        reproducible-signing: on
        nsec3: on
        cds-cdnskey-publish: delete-dnssec
        zsk-lifetime: 30d
        ksk-submission: zone
        nsec3-iterations: 10

    template:
      - id: zone
        storage: /zones
        file: %s.zone
        dnssec-signing: on
        dnssec-policy: zone
        acl: [secondary-xfr, netnod-xfr]
        notify: [notify-sidecar, netnod-dist-1, netnod-dist-2]
        zonefile-sync: -1
        zonefile-load: difference-no-serial
        journal-content: all
        semantic-checks: on
        serial-policy: dateserial

      - id: zone-cds-disable
        storage: /zones
        file: %s.zone
        dnssec-signing: on
        dnssec-policy: zone-cds-disable
        acl: [secondary-xfr, netnod-xfr]
        notify: [notify-sidecar, netnod-dist-1, netnod-dist-2]
        zonefile-sync: -1
        zonefile-load: difference-no-serial
        journal-content: all
        semantic-checks: on
        serial-policy: dateserial

      - id: zone-secondary
        storage: /zones
        file: %s.zone
        dnssec-signing: off
        acl: [secondary-xfr, netnod-xfr]
        notify: [notify-sidecar, netnod-dist-1, netnod-dist-2]
        zonefile-sync: -1
        zonefile-load: difference-no-serial
        journal-content: all
        semantic-checks: on
        serial-policy: dateserial

    zone:
      - domain: catalog.dns.as207960.ltd.uk.
        file: /zones/catalog.zone
        catalog-role: interpret
        catalog-template: [ zone, zone-cds-disable, zone-secondary ]
        acl: secondary-xfr
        notify: notify-sidecar
        semantic-checks: on
        serial-policy: dateserial
    
      - domain: cds-always.dns.as207960.ltd.uk.
        template: zone
        file: /zones/cds-always.dns.as207960.ltd.uk.zone
    
      - domain: cds-delete.dns.as207960.ltd.uk.
        template: zone-cds-disable
        file: /zones/cds-delete.dns.as207960.ltd.uk.zone
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hexdns-knot-primary
  labels:
    app: hexdns
    part: knot
    role: primary
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: hexdns
      part: knot
      role: primary
  template:
    metadata:
      annotations:
        cni.projectcalico.org/ipv6pools: "[\"hexdns-primary-ip6-ippool\"]"
      labels:
        app: hexdns
        part: knot
        role: primary
    spec:
      volumes:
        - name: zones
          persistentVolumeClaim:
            claimName: hexdns-zones
        - name: knot
          persistentVolumeClaim:
            claimName: hexdns-knot
        - name: config
          configMap:
            name: hexdns-knot
        - name: rundir
          emptyDir: {}
        - name: devfuse
          hostPath:
            path: /dev/fuse
        - name: zones-s3
          emptyDir: {}
      containers:
        - name: s3
          image: as207960/goofys
          args: ["goofys" "-f", "--endpoint", "$ENDPOINT", "--region", "$REGION",
            "$BUCKET", "/mnt/s3"]
          securityContext:
            privileged: true
          envFrom:
            - secretRef:
                name: hexdns-zone-s3
          volumeMounts:
            - name: devfuse
              mountPath: /dev/fuse
            - name: zones-s3
              mountPath: /mnt/s3
        - name: knot
          image: as207960/knotd:6
          imagePullPolicy: Always
          command: [
            "sh", "-c",
            "cp /config-template/knot.conf /config/knot.conf &&
             sed -i \"s/(xfr-secret)/$XFR_SECRET/g\" /config/knot.conf &&
             sed -i \"s/(netnod-xfr-secret)/$NETNOD_XFR_SECRET/g\" /config/knot.conf &&
             sed -i \"s/(unbound-no-dns64)/$HEXDNS_UNBOUND_NO_DNS64_SERVICE_HOST/g\" /config/knot.conf &&
             sleep 15;
             while true; do rm /rundir/knot.pid; knotd; done"
          ]
          readinessProbe:
            tcpSocket:
              port: 53
            initialDelaySeconds: 15
            periodSeconds: 10
          volumeMounts:
            - mountPath: "/zones/"
              name: zones
            - mountPath: "/storage/"
              name: knot
            - mountPath: "/config-template/"
              name: config
            - mountPath: "/rundir/"
              name: rundir
          envFrom:
            - secretRef:
                name: hexdns-knot-xfr
        - name: reloader
          image: as207960/hexdns-knot-sidecar:(version)
          imagePullPolicy: Always
          command: ["python3", "/app/sidecar.py"]
          volumeMounts:
            - mountPath: "/rundir/"
              name: rundir
          envFrom:
            - secretRef:
                name: hexdns-rpc
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: hexdns-knot-primary
spec:
  podSelector:
    matchLabels:
      app: hexdns
      part: knot
      role: primary
  policyTypes:
  - Ingress
  ingress:
  - ports:
    - protocol: TCP
      port: 53
    - protocol: UDP
      port: 53
---
apiVersion: v1
kind: Service
metadata:
  name: hexdns-knot-primary
spec:
  selector:
    app: hexdns
    part: knot
    role: primary
  ports:
    - port: 53
      targetPort: 53
      protocol: UDP
      name: dns-udp
    - port: 53
      targetPort: 53
      protocol: TCP
      name: dns-tcp
---
apiVersion: v1
kind: Service
metadata:
  name: hexdns-knot-primary-ext-udp
  annotations:
    metallb.universe.tf/allow-shared-ip: "hexdns-knot-primary-ext"
spec:
  type: LoadBalancer
  externalTrafficPolicy: Local
  selector:
    app: hexdns
    part: knot
    role: primary
  ports:
    - port: 53
      targetPort: 53
      protocol: UDP
---
apiVersion: v1
kind: Service
metadata:
  name: hexdns-knot-primary-ext-tcp
  annotations:
    metallb.universe.tf/allow-shared-ip: "hexdns-knot-primary-ext"
spec:
  type: LoadBalancer
  externalTrafficPolicy: Local
  selector:
    app: hexdns
    part: knot
    role: primary
  ports:
    - port: 53
      targetPort: 53
      protocol: TCP
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: hexdns-knot-secondary
data:
  knot.conf: |
    server:
        identity: "HexDNS"
        listen: 0.0.0.0@53
        listen: ::@53
        nsid: (nsid)
        key-file: /quic/tls.key
        cert-file: /quic/tls.crt
        rundir: /rundir/
    
    xdp:
        listen: eth0
        udp: on
        tcp: off
        quic: on

    database:
        journal-db-mode: asynchronous

    log:
      - target: stdout
        any: info
    
    key:
      - id: secondary-xfr
        algorithm: hmac-sha256
        secret: (xfr-secret)
    
    remote:
      - id: primary
        address: (primary-address)
        key: secondary-xfr
      - id: ddns-primary
        address: (ddns-primary-address)
    
    mod-updateproxy:
      - id: default
        remote: ddns-primary
        timeout: 5000

    mod-queryignoretsig:
      - id: default

    mod-stats:
      - id: custom
        flag-presence: on
        reply-nodata: on
        query-size: on
        reply-size: on
        edns-presence: on
        query-type: on
        request-edns-option: on
        response-edns-option: on
        reply-nodata: on
    
    mod-rrl:
      - id: default
        rate-limit: 200
        slip: 2
      
    acl:
      - id: notify
        address: 127.0.0.1
        action: notify

    template:
      - id: default
        global-module: [ mod-rrl/default, mod-stats/custom ]

      - id: zone
        journal-content: none
        master: primary
        module: [ mod-updateproxy/default, mod-queryignoretsig/default, mod-stats/custom ]
        acl: notify

    zone:
      - domain: catalog.dns.as207960.ltd.uk.
        master: primary
        catalog-role: interpret
        catalog-template: zone
        acl: notify
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hexdns-knot-secondary
  labels:
    app: hexdns
    part: knot
    role: secondary
spec:
  replicas: 6
  selector:
    matchLabels:
      app: hexdns
      part: knot
      role: secondary
  template:
    metadata:
      annotations:
        cni.projectcalico.org/ipv6pools: "[\"default-ipv6-ippool\"]"
      labels:
        app: hexdns
        part: knot
        role: secondary
    spec:
      tolerations:
        - key: special
          operator: Equal
          value: edge
          effect: NoSchedule
      volumes:
        - name: knot
          emptyDir: {}
        - name: config
          configMap:
            name: hexdns-knot-secondary
        - name: rundir
          emptyDir: {}
        - name: quic-keys
          secret:
              secretName: hexdns-quic
      containers:
        - name: knot
          image: as207960/knotd:7
          imagePullPolicy: Always
          command: [
            "sh", "-c",
            "cp /config-template/knot.conf /config/knot.conf &&
             sed -i \"s/(xfr-secret)/$XFR_SECRET/g\" /config/knot.conf &&
             sed -i \"s/(primary-address)/$HEXDNS_KNOT_PRIMARY_SERVICE_HOST/g\" /config/knot.conf &&
             sed -i \"s/(ddns-primary-address)/$HEXDNS_UPDATE_SERVICE_HOST/g\" /config/knot.conf &&
             sed -i \"s/(nsid)/$HOSTNAME/g\" /config/knot.conf &&
             sleep 15 &&
             while true; do rm /rundir/knot.pid; knotd; done"
          ]
          readinessProbe:
            tcpSocket:
              port: 53
            initialDelaySeconds: 15
            periodSeconds: 10
          volumeMounts:
            - mountPath: "/storage/"
              name: knot
            - mountPath: "/config-template/"
              name: config
            - mountPath: "/rundir/"
              name: rundir
            - mountPath: "/quic/"
              name: quic-keys
          envFrom:
            - secretRef:
                name: hexdns-knot-xfr
          securityContext:
            capabilities:
              add: [ "NET_RAW", "NET_ADMIN", "SYS_ADMIN", "IPC_LOCK", "SYS_RESOURCE" ]
        - name: reloader
          image: as207960/hexdns-knot-sidecar-secondary:(version)
          imagePullPolicy: Always
          command: ["python3", "/app/sidecar-secondary.py"]
          envFrom:
            - secretRef:
                name: hexdns-rpc
        - name: exporter
          image: as207960/knot-exporter:2
          imagePullPolicy: Always
          command: [
            "sh", "-c",
            "sleep 20 && 
            python3 /app/knot_exporter --web-listen-addr :: --knot-socket-path /rundir/knot.sock --knot-library-path /usr/lib/x86_64-linux-gnu/libknot.so.11"
          ]
          readinessProbe:
            tcpSocket:
              port: 9433
            initialDelaySeconds: 15
            periodSeconds: 10
          volumeMounts:
            - mountPath: "/rundir/"
              name: rundir
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: hexdns-knot-secondary
spec:
  podSelector:
    matchLabels:
      app: hexdns
      part: knot
      role: secondary
  policyTypes:
  - Ingress
  ingress:
  - ports:
    - protocol: TCP
      port: 53
    - protocol: UDP
      port: 53
    - protocol: UDP
      port: 853
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: hexdns-quic-cert
spec:
  secretName: hexdns-quic
  duration: 2160h
  renewBefore: 360h
  commonName: ns1.as207960.net
  isCA: false
  privateKey:
    size: 384
    algorithm: ECDSA
  usages:
    - server auth
  dnsNames:
    - ns1.as207960.net
    - ns2.as207960.net
  issuerRef:
    name: gts-as207960-ltd-uk
    kind: ClusterIssuer
    group: cert-manager.io
