apiVersion: crd.projectcalico.org/v1
kind: IPPool
metadata:
  name: hexdns-primary-ip6-ippool
spec:
  blockSize: 127
  cidr: 2001:678:fc8:2::18/126
  disabled: false
  nodeSelector: "!all()"
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: hexdns-knot
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: hexdns-knot
data:
  knot.conf: |
    server:
        identity: "HexDNS"
        listen: 0.0.0.0@53
        listen: ::@53
        background-workers: 1
        rundir: /rundir/

    database:
        journal-db-mode: robust

    log:
      - target: stdout
        any: info
    
    key:
      - id: secondary-xfr
        algorithm: hmac-sha256
        secret: (xfr-secret)
      - id: netnod-cyfyngedig-1.
        algorithm: hmac-sha512
        secret: (netnod-xfr-secret)
      - id: tsig.kube-cluster.as207960.net.
        algorithm: hmac-sha256
        secret: (coredns-xfr-secret)
    
    acl:
      - id: secondary-xfr
        action: transfer
        key: secondary-xfr
      - id: netnod-xfr
        action: transfer
        key: netnod-cyfyngedig-1.
      - id: coredns-notify
        address: 2a0e:1cc1:1:0:8000::/65
        action: notify
    
    remote:
      - id: unbound-no-dns64
        address: (unbound-no-dns64)@5053
      - id: notify-sidecar
        address: 127.0.0.1@5353
      - id: netnod-dist-1
        address: 2a01:3f0:0:27::24
        key: netnod-cyfyngedig-1.
      - id: netnod-dist-2
        address: 2a01:3f0:0:28::25
        key: netnod-cyfyngedig-1.
      - id: coredns
        address: 2a0d:1a40:7901::2
        key: tsig.kube-cluster.as207960.net.
    
    submission:
      - id: zone
        parent: unbound-no-dns64
        check-interval: 15m

    policy:
      - id: zone
        signing-threads: 4
        algorithm: ecdsap256sha256
        ksk-shared: on
        dnskey-ttl: 86400
        reproducible-signing: on
        nsec3: on
        cds-cdnskey-publish: always
        zsk-lifetime: 30d
        ksk-submission: zone
        nsec3-iterations: 10
        dnskey-management: incremental
        delete-delay: 30d

    template:
      - id: zone
        storage: /zones
        file: %s.zone.signed
        dnssec-signing: off
        zonefile-sync: -1
        zonefile-load: whole
        journal-content: none
        semantic-checks: on
        acl: [secondary-xfr, netnod-xfr]
        notify: [notify-sidecar, netnod-dist-1, netnod-dist-2]

      - id: zone-secondary
        storage: /zones
        file: %s.zone
        dnssec-signing: off
        zonefile-sync: -1
        zonefile-load: whole
        journal-content: none
        semantic-checks: on
        acl: [secondary-xfr, netnod-xfr]
        notify: [notify-sidecar, netnod-dist-1, netnod-dist-2]

      - id: zone-k8s
        storage: /zones
        file: %s.zone
        dnssec-signing: on
        dnssec-policy: zone
        master: coredns
        acl: [secondary-xfr, netnod-xfr, coredns-notify]
        notify: [notify-sidecar, netnod-dist-1, netnod-dist-2]
        zonefile-sync: 0
        zonefile-load: whole
        journal-content: changes
        semantic-checks: on
        serial-policy: dateserial
    
    zone:
      - domain: catalog.dns.as207960.ltd.uk.
        file: /zones/catalog.zone
        catalog-role: interpret
        catalog-template: [ zone, zone-secondary ]
        acl: secondary-xfr
        notify: notify-sidecar
        semantic-checks: on
        zonefile-sync: -1
        zonefile-load: whole
        journal-content: none
        dnssec-signing: off
    
      - domain: cds-always.dns.as207960.ltd.uk.
        template: zone
        file: /zones/cds-always.dns.as207960.ltd.uk.zone
    
      - domain: cds-delete.dns.as207960.ltd.uk.
        template: zone
        file: /zones/cds-delete.dns.as207960.ltd.uk.zone
    
      - domain: kube-cluster.as207960.net
        template: zone-k8s
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hexdns-knot-primary
  labels:
    app: hexdns
    part: knot
    role: primary
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: hexdns
      part: knot
      role: primary
  template:
    metadata:
      annotations:
        cni.projectcalico.org/ipv6pools: "[\"hexdns-primary-ip6-ippool\"]"
        prometheus.io/scrape: "true"
        prometheus.io/port: "9433"
        prometheus.io/path: "/metrics"
      labels:
        app: hexdns
        part: knot
        role: primary
    spec:
      volumes:
        - name: knot
          persistentVolumeClaim:
            claimName: hexdns-knot
        - name: config
          configMap:
            name: hexdns-knot
        - name: rundir
          emptyDir: {}
        - name: devfuse
          hostPath:
            path: /dev/fuse
        - name: zones
          emptyDir: {}
      containers:
        - name: knot
          image: as207960/knotd:9
          imagePullPolicy: IfNotPresent
          command: [
            "sh", "-c",
            "sleep 30 &&
             cp /config-template/knot.conf /config/knot.conf &&
             sed -i \"s/(xfr-secret)/$XFR_SECRET/g\" /config/knot.conf &&
             sed -i \"s/(netnod-xfr-secret)/$NETNOD_XFR_SECRET/g\" /config/knot.conf &&
             sed -i \"s/(coredns-xfr-secret)/$COREDNS_XFR_SECRET/g\" /config/knot.conf &&
             sed -i \"s/(unbound-no-dns64)/$HEXDNS_UNBOUND_NO_DNS64_SERVICE_HOST/g\" /config/knot.conf &&
             while true; do rm /rundir/knot.pid; knotd; done"
          ]
          readinessProbe:
            tcpSocket:
              port: 53
            initialDelaySeconds: 15
            periodSeconds: 10
          securityContext:
            privileged: true
          volumeMounts:
            - mountPath: /zones
              name: zones
              mountPropagation: Bidirectional
              readOnly: true
            - mountPath: "/storage/"
              name: knot
            - mountPath: "/config-template/"
              name: config
            - mountPath: "/rundir/"
              name: rundir
          envFrom:
            - secretRef:
                name: hexdns-knot-xfr
        - name: reloader
          image: as207960/hexdns-knot-sidecar:(version)
          imagePullPolicy: IfNotPresent
          command: [
            "python3", "/app/sidecar.py"
          ]
          securityContext:
            privileged: true
          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
          volumeMounts:
            - mountPath: "/rundir/"
              name: rundir
            - mountPath: /zones
              name: zones
              mountPropagation: Bidirectional
              readOnly: true
          envFrom:
            - secretRef:
                name: hexdns-rpc
        - name: s3-zones
          image: as207960/goofys
          imagePullPolicy: IfNotPresent
          args: ["-c", "goofys -f --endpoint $ENDPOINT --region $REGION $BUCKET /mnt/s3"]
          lifecycle:
            preStop:
              exec:
                command: ["umount", "/mnt/s3"]
          securityContext:
            privileged: true
          envFrom:
            - secretRef:
                name: hexdns-zone-s3
          volumeMounts:
            - name: devfuse
              mountPath: /dev/fuse
            - name: zones
              mountPath: /mnt/s3
              mountPropagation: Bidirectional
#        - name: s3-state
#          image: efrecon/s3fs
#          securityContext:
#            privileged: true
#          envFrom:
#            - secretRef:
#                name: hexdns-zone-s3
#          volumeMounts:
#            - name: devfuse
#              mountPath: /dev/fuse
#            - name: zones
#              mountPath: /mnt/s3
#              mountPropagation: Bidirectional
        - name: exporter
          image: as207960/knot-exporter:2
          imagePullPolicy: IfNotPresent
          command: [
            "sh", "-c",
            "sleep 60 &&
              python3 /app/knot_exporter --web-listen-addr :: --knot-socket-path /rundir/knot.sock --knot-library-path /usr/lib/x86_64-linux-gnu/libknot.so.11"
          ]
          readinessProbe:
            tcpSocket:
              port: 9433
            initialDelaySeconds: 15
            periodSeconds: 10
          volumeMounts:
            - mountPath: "/rundir/"
              name: rundir
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: hexdns-knot-primary
spec:
  podSelector:
    matchLabels:
      app: hexdns
      part: knot
      role: primary
  policyTypes:
  - Ingress
  ingress:
  - ports:
    - protocol: TCP
      port: 53
    - protocol: UDP
      port: 53
  - from:
      - namespaceSelector:
          matchLabels:
            role: metrics
    ports:
      - protocol: TCP
        port: 9433
---
apiVersion: v1
kind: Service
metadata:
  name: hexdns-knot-primary
spec:
  selector:
    app: hexdns
    part: knot
    role: primary
  ports:
    - port: 53
      targetPort: 53
      protocol: UDP
      name: dns-udp
    - port: 53
      targetPort: 53
      protocol: TCP
      name: dns-tcp
---
apiVersion: v1
kind: Service
metadata:
  name: hexdns-knot-primary-ext-udp
  annotations:
    metallb.universe.tf/allow-shared-ip: "hexdns-knot-primary-ext"
spec:
  type: LoadBalancer
  externalTrafficPolicy: Local
  selector:
    app: hexdns
    part: knot
    role: primary
  ports:
    - port: 53
      targetPort: 53
      protocol: UDP
---
apiVersion: v1
kind: Service
metadata:
  name: hexdns-knot-primary-ext-tcp
  annotations:
    metallb.universe.tf/allow-shared-ip: "hexdns-knot-primary-ext"
spec:
  type: LoadBalancer
  externalTrafficPolicy: Local
  selector:
    app: hexdns
    part: knot
    role: primary
  ports:
    - port: 53
      targetPort: 53
      protocol: TCP