kind: ConfigMap
apiVersion: v1
metadata:
  name: hexdns-knot-secondary
data:
  knot.conf: |
    server:
        identity: "HexDNS"
        listen: 0.0.0.0@53
        listen: ::@53
        listen-tls: 0.0.0.0@853
        listen-tls: ::@853
        nsid: (nsid)
        key-file: /quic/tls.key
        cert-file: /quic/tls.crt
        rundir: /rundir/
    
    xdp:
        listen: eth0
        udp: on
        tcp: off
        quic: on

    database:
        journal-db-mode: asynchronous

    log:
      - target: stdout
        any: info
    
    key:
      - id: secondary-xfr
        algorithm: hmac-sha256
        secret: (xfr-secret)
    
    remote:
      - id: primary
        address: (primary-address)
        key: secondary-xfr
      - id: ddns-primary
        address: (ddns-primary-address)
    
    mod-updateproxy:
      - id: default
        remote: ddns-primary
        timeout: 5000

    mod-queryignoretsig:
      - id: default

    mod-stats:
      - id: custom
        flag-presence: on
        reply-nodata: on
        query-size: on
        reply-size: on
        edns-presence: on
        query-type: on
        request-edns-option: on
        response-edns-option: on
        reply-nodata: on
    
    mod-rrl:
      - id: default
        rate-limit: 200
        slip: 2
      
    acl:
      - id: notify
        address: 127.0.0.1
        action: notify

    template:
      - id: default
        global-module: [ mod-rrl/default, mod-stats/custom ]

      - id: zone
        journal-content: none
        master: primary
        module: [ mod-updateproxy/default, mod-queryignoretsig/default, mod-stats/custom ]
        acl: notify

    zone:
      - domain: catalog.dns.as207960.ltd.uk.
        master: primary
        catalog-role: interpret
        catalog-template: zone
        acl: notify
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: hexdns-knot-secondary
  labels:
    app: hexdns
    part: knot
    role: secondary
spec:
  selector:
    matchLabels:
      app: hexdns
      part: knot
      role: secondary
  template:
    metadata:
      annotations:
        cni.projectcalico.org/ipv6pools: "[\"default-ipv6-ippool\"]"
        prometheus.io/scrape: "true"
        prometheus.io/port: "9433"
        prometheus.io/path: "/metrics"
      labels:
        app: hexdns
        part: knot
        role: secondary
    spec:
      tolerations:
        - key: special
          operator: Equal
          value: edge
          effect: NoSchedule
      volumes:
        - name: knot
          emptyDir: {}
        - name: config
          configMap:
            name: hexdns-knot-secondary
        - name: rundir
          emptyDir: {}
        - name: quic-keys
          secret:
              secretName: hexdns-quic
      containers:
        - name: knot
          image: as207960/knotd:9
          imagePullPolicy: IfNotPresent
          command: [
            "sh", "-c",
            "cp /config-template/knot.conf /config/knot.conf &&
             sed -i \"s/(xfr-secret)/$XFR_SECRET/g\" /config/knot.conf &&
             sed -i \"s/(primary-address)/$HEXDNS_KNOT_PRIMARY_SERVICE_HOST/g\" /config/knot.conf &&
             sed -i \"s/(ddns-primary-address)/$HEXDNS_UPDATE_SERVICE_HOST/g\" /config/knot.conf &&
             sed -i \"s/(nsid)/$HOSTNAME/g\" /config/knot.conf &&
             sleep 15 &&
             while true; do rm /rundir/knot.pid; knotd; done"
          ]
          readinessProbe:
            tcpSocket:
              port: 53
            initialDelaySeconds: 15
            periodSeconds: 10
          volumeMounts:
            - mountPath: "/storage/"
              name: knot
            - mountPath: "/config-template/"
              name: config
            - mountPath: "/rundir/"
              name: rundir
            - mountPath: "/quic/"
              name: quic-keys
          envFrom:
            - secretRef:
                name: hexdns-knot-xfr
          securityContext:
            capabilities:
              add: [ "NET_RAW", "NET_ADMIN", "SYS_ADMIN", "IPC_LOCK", "SYS_RESOURCE" ]
        - name: reloader
          image: as207960/hexdns-knot-sidecar-secondary:(version)
          imagePullPolicy: IfNotPresent
          command: ["python3", "/app/sidecar-secondary.py"]
          envFrom:
            - secretRef:
                name: hexdns-rpc
        - name: exporter
          image: as207960/knot-exporter:6
          imagePullPolicy: IfNotPresent
          command: [
            "sh", "-c",
            "sleep 20 && 
            python3 /app/knot_exporter --web-listen-addr :: --knot-socket-path /rundir/knot.sock --knot-library-path /usr/lib/x86_64-linux-gnu/libknot.so.13"
          ]
          readinessProbe:
            tcpSocket:
              port: 9433
            initialDelaySeconds: 15
            periodSeconds: 10
          volumeMounts:
            - mountPath: "/rundir/"
              name: rundir
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: hexdns-knot-secondary
spec:
  podSelector:
    matchLabels:
      app: hexdns
      part: knot
      role: secondary
  policyTypes:
    - Ingress
  ingress:
    - ports:
        - protocol: TCP
          port: 53
        - protocol: UDP
          port: 53
        - protocol: TCP
          port: 853
        - protocol: UDP
          port: 853
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: hexdns-knot-secondary-metrics
spec:
  podSelector:
    matchLabels:
      app: hexdns
      part: knot
      role: secondary
  policyTypes:
    - Ingress
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              role: metrics
      ports:
        - protocol: TCP
          port: 9433
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: hexdns-quic-cert
spec:
  secretName: hexdns-quic
  duration: 2160h
  renewBefore: 360h
  commonName: ns1.as207960.net
  isCA: false
  privateKey:
    size: 384
    algorithm: ECDSA
  usages:
    - server auth
  dnsNames:
    - ns1.as207960.net
    - ns2.as207960.net
  issuerRef:
    name: gts-as207960-ltd-uk
    kind: ClusterIssuer
    group: cert-manager.io
