kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: hexdns-knot
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: hexdns-knot
data:
  knot.conf: |
    server:
        identity: "HexDNS"
        listen: 0.0.0.0@53
        listen: ::@53

    database:
        journal-db-mode: asynchronous

    log:
      - target: stdout
        any: info
    
    key:
      - id: secondary-xfr
        algorithm: hmac-sha256
        secret: (xfr-secret)
    
    acl:
      - id: secondary-xfr
        action: transfer
        key: secondary-xfr
    
    remote:
      - id: unbound-no-dns64
        address: (unbound-no-dns64)@5053
      - id: notify-sidecar
        address: 127.0.0.1@5353
    
    submission:
      - id: zone
        parent: unbound-no-dns64
        check-interval: 15m

    policy:
      - id: zone
        signing-threads: 4
        algorithm: ecdsap256sha256
        ksk-shared: on
        dnskey-ttl: 86400
        reproducible-signing: on
        nsec3: on
        cds-cdnskey-publish: always
        zsk-lifetime: 30d
        ksk-submission: zone
        nsec3-iterations: 10
    
      - id: zone-cds-disable
        signing-threads: 4
        algorithm: ecdsap256sha256
        ksk-shared: on
        dnskey-ttl: 86400
        reproducible-signing: on
        nsec3: on
        cds-cdnskey-publish: delete-dnssec
        zsk-lifetime: 30d
        ksk-submission: zone
        nsec3-iterations: 10

    template:
      - id: zone
        storage: /zones
        file: %s.zone
        journal-content: none
        dnssec-signing: on
        dnssec-policy: zone
        acl: secondary-xfr
        notify: notify-sidecar

    template:
      - id: zone-cds-disable
        storage: /zones
        file: %s.zone
        journal-content: none
        dnssec-signing: on
        dnssec-policy: zone-cds-disable
        acl: secondary-xfr
        notify: notify-sidecar

    template:
      - id: zone-secondary
        storage: /zones
        file: %s.zone
        journal-content: none
        dnssec-signing: off
        acl: secondary-xfr
        notify: notify-sidecar

    zone:
      - domain: catalog.dns.as207960.ltd.uk.
        file: /zones/catalog.zone
        catalog-role: interpret
        catalog-template: [ zone, zone-cds-disable, zone-secondary ]
        acl: secondary-xfr
        notify: notify-sidecar
    
      - domain: cds-always.dns.as207960.ltd.uk.
        template: zone
        file: /zones/cds-always.dns.as207960.ltd.uk.zone
    
      - domain: cds-delete.dns.as207960.ltd.uk.
        template: zone-cds-disable
        file: /zones/cds-delete.dns.as207960.ltd.uk.zone
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hexdns-knot-primary
  labels:
    app: hexdns
    part: knot
    role: primary
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: hexdns
      part: knot
      role: primary
  template:
    metadata:
      annotations:
        cni.projectcalico.org/ipv6pools: "[\"default-ipv6-ippool\"]"
      labels:
        app: hexdns
        part: knot
        role: primary
    spec:
      volumes:
        - name: zones
          persistentVolumeClaim:
            claimName: hexdns-zones
        - name: knot
          persistentVolumeClaim:
            claimName: hexdns-knot
        - name: config
          configMap:
            name: hexdns-knot
        - name: rundir
          emptyDir: {}
      containers:
        - name: knot
          image: as207960/knotd:1
          imagePullPolicy: Always
          command: [
            "sh", "-c",
            "cp /config-template/knot.conf /config/knot.conf &&
             sed -i \"s/(xfr-secret)/$XFR_SECRET/g\" /config/knot.conf &&
             sed -i \"s/(unbound-no-dns64)/$HEXDNS_UNBOUND_NO_DNS64_SERVICE_HOST/g\" /config/knot.conf &&
             sleep 15 &&
             /rundir/knot.pid;
             knotd"
          ]
          readinessProbe:
            tcpSocket:
              port: 53
            initialDelaySeconds: 15
            periodSeconds: 10
          volumeMounts:
            - mountPath: "/zones/"
              name: zones
            - mountPath: "/storage/"
              name: knot
            - mountPath: "/config-template/"
              name: config
            - mountPath: "/rundir/"
              name: rundir
          envFrom:
            - secretRef:
                name: hexdns-knot-xfr
        - name: reloader
          image: as207960/hexdns-knot-sidecar:(version)
          imagePullPolicy: Always
          command: ["python3", "/app/sidecar.py"]
          volumeMounts:
            - mountPath: "/rundir/"
              name: rundir
          envFrom:
            - secretRef:
                name: hexdns-rpc
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: hexdns-knot-primary
spec:
  podSelector:
    matchLabels:
      app: hexdns
      part: knot
      role: primary
  policyTypes:
  - Ingress
  ingress:
  - ports:
    - protocol: TCP
      port: 53
    - protocol: UDP
      port: 53
---
apiVersion: v1
kind: Service
metadata:
  name: hexdns-knot-primary
spec:
  selector:
    app: hexdns
    part: knot
    role: primary
  ports:
    - port: 53
      targetPort: 53
      protocol: UDP
      name: dns-udp
    - port: 53
      targetPort: 53
      protocol: TCP
      name: dns-tcp
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: hexdns-knot-secondary
data:
  knot.conf: |
    server:
        identity: "HexDNS"
        listen: 0.0.0.0@53
        listen: ::@53
        nsid: (nsid)

    database:
        journal-db-mode: asynchronous

    log:
      - target: stdout
        any: info
    
    key:
      - id: secondary-xfr
        algorithm: hmac-sha256
        secret: (xfr-secret)
    
    remote:
      - id: primary
        address: (primary-address)
        key: secondary-xfr
      - id: ddns-primary
        address: (ddns-primary-address)
    
    mod-updateproxy:
      - id: default
        remote: ddns-primary
        timeout: 5000

    mod-queryignoretsig:
      - id: default

    mod-stats:
      - id: custom
        flag-presence: on
        reply-nodata: on
        query-size: on
        reply-size: on
        edns-presence: on
        query-type: on

    acl:
      - id: notify
        address: 127.0.0.1
        action: notify

    template:
      - id: default
        global-module: mod-stats/custom

      - id: zone
        journal-content: none
        master: primary
        module: [ mod-updateproxy/default, mod-queryignoretsig/default ]
        acl: notify

    zone:
      - domain: catalog.dns.as207960.ltd.uk.
        master: primary
        catalog-role: interpret
        catalog-template: zone
        acl: notify
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hexdns-knot-secondary
  labels:
    app: hexdns
    part: knot
    role: secondary
spec:
  replicas: 6
  selector:
    matchLabels:
      app: hexdns
      part: knot
      role: secondary
  template:
    metadata:
      annotations:
        cni.projectcalico.org/ipv6pools: "[\"default-ipv6-ippool\"]"
      labels:
        app: hexdns
        part: knot
        role: secondary
    spec:
      tolerations:
        - key: special
          operator: Equal
          value: edge
          effect: NoSchedule
      volumes:
        - name: knot
          emptyDir: {}
        - name: config
          configMap:
            name: hexdns-knot-secondary
        - name: rundir
          emptyDir: {}
      containers:
        - name: knot
          image: as207960/knotd:2
          imagePullPolicy: Always
          command: [
            "sh", "-c",
            "cp /config-template/knot.conf /config/knot.conf &&
             sed -i \"s/(xfr-secret)/$XFR_SECRET/g\" /config/knot.conf &&
             sed -i \"s/(primary-address)/$HEXDNS_KNOT_PRIMARY_SERVICE_HOST/g\" /config/knot.conf &&
             sed -i \"s/(ddns-primary-address)/$HEXDNS_UPDATE_SERVICE_HOST/g\" /config/knot.conf &&
             sed -i \"s/(nsid)/$HOSTNAME/g\" /config/knot.conf &&
             sleep 15 &&
             knotd"
          ]
          readinessProbe:
            tcpSocket:
              port: 53
            initialDelaySeconds: 15
            periodSeconds: 10
          volumeMounts:
            - mountPath: "/storage/"
              name: knot
            - mountPath: "/config-template/"
              name: config
            - mountPath: "/rundir/"
              name: rundir
          envFrom:
            - secretRef:
                name: hexdns-knot-xfr
        - name: reloader
          image: as207960/hexdns-knot-sidecar-secondary:(version)
          imagePullPolicy: Always
          command: ["python3", "/app/sidecar-secondary.py"]
          envFrom:
            - secretRef:
                name: hexdns-rpc
        - name: exporter
          image: as207960/knot-exporter:2
          imagePullPolicy: Always
          command: [
            "sh", "-c",
            "sleep 20 && 
            python3 /app/knot_exporter --web-listen-addr :: --knot-socket-path /rundir/knot.sock --knot-library-path /usr/lib/x86_64-linux-gnu/libknot.so.11"
          ]
          readinessProbe:
            tcpSocket:
              port: 9433
            initialDelaySeconds: 15
            periodSeconds: 10
          volumeMounts:
            - mountPath: "/rundir/"
              name: rundir
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: hexdns-knot-secondary
spec:
  podSelector:
    matchLabels:
      app: hexdns
      part: knot
      role: secondary
  policyTypes:
  - Ingress
  ingress:
  - ports:
    - protocol: TCP
      port: 53
    - protocol: UDP
      port: 53
---
apiVersion: v1
kind: Service
metadata:
  name: hexdns-knot-secondary-udp
  annotations:
    metallb.universe.tf/allow-shared-ip: "hexdns-knot"
spec:
  type: LoadBalancer
  externalTrafficPolicy: Local
  selector:
    app: hexdns
    part: knot
    role: secondary
  ports:
    - port: 53
      targetPort: 53
      protocol: UDP
      name: dns-udp
---
apiVersion: v1
kind: Service
metadata:
  name: hexdns-knot-secondary-tcp
  annotations:
    metallb.universe.tf/allow-shared-ip: "hexdns-knot"
spec:
  type: LoadBalancer
  externalTrafficPolicy: Local
  selector:
    app: hexdns
    part: knot
    role: secondary
  ports:
    - port: 53
      targetPort: 53
      protocol: TCP
      name: dns-tcp
