"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
import builtins
import google.protobuf.descriptor
import google.protobuf.message
import sys

if sys.version_info >= (3, 8):
    import typing as typing_extensions
else:
    import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing_extensions.final
class TSIGRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    KEY_NAME_FIELD_NUMBER: builtins.int
    key_name: builtins.str
    def __init__(
        self,
        *,
        key_name: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["key_name", b"key_name"]) -> None: ...

global___TSIGRequest = TSIGRequest

@typing_extensions.final
class TSIGSecret(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    SECRET_FIELD_NUMBER: builtins.int
    secret: builtins.bytes
    def __init__(
        self,
        *,
        secret: builtins.bytes = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["secret", b"secret"]) -> None: ...

global___TSIGSecret = TSIGSecret

@typing_extensions.final
class IPACLRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ZONE_NAME_FIELD_NUMBER: builtins.int
    V4_FIELD_NUMBER: builtins.int
    V6_FIELD_NUMBER: builtins.int
    zone_name: builtins.str
    v4: builtins.int
    v6: builtins.bytes
    def __init__(
        self,
        *,
        zone_name: builtins.str = ...,
        v4: builtins.int = ...,
        v6: builtins.bytes = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["ip_addr", b"ip_addr", "v4", b"v4", "v6", b"v6"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["ip_addr", b"ip_addr", "v4", b"v4", "v6", b"v6", "zone_name", b"zone_name"]) -> None: ...
    def WhichOneof(self, oneof_group: typing_extensions.Literal["ip_addr", b"ip_addr"]) -> typing_extensions.Literal["v4", "v6"] | None: ...

global___IPACLRequest = IPACLRequest

@typing_extensions.final
class IPACLResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ALLOWED_FIELD_NUMBER: builtins.int
    allowed: builtins.bool
    def __init__(
        self,
        *,
        allowed: builtins.bool = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["allowed", b"allowed"]) -> None: ...

global___IPACLResponse = IPACLResponse

@typing_extensions.final
class Notify(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    SERVER_FIELD_NUMBER: builtins.int
    PORT_FIELD_NUMBER: builtins.int
    ZONE_FIELD_NUMBER: builtins.int
    server: builtins.str
    port: builtins.int
    zone: builtins.str
    def __init__(
        self,
        *,
        server: builtins.str = ...,
        port: builtins.int = ...,
        zone: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["port", b"port", "server", b"server", "zone", b"zone"]) -> None: ...

global___Notify = Notify
