# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from . import axfr_pb2 as axfr__pb2


class AXFRServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetTSIGSecret = channel.unary_unary(
                '/as207960.dns.axfr.AXFRService/GetTSIGSecret',
                request_serializer=axfr__pb2.TSIGRequest.SerializeToString,
                response_deserializer=axfr__pb2.TSIGSecret.FromString,
                )
        self.CheckIPACL = channel.unary_unary(
                '/as207960.dns.axfr.AXFRService/CheckIPACL',
                request_serializer=axfr__pb2.IPACLRequest.SerializeToString,
                response_deserializer=axfr__pb2.IPACLResponse.FromString,
                )


class AXFRServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetTSIGSecret(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CheckIPACL(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AXFRServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetTSIGSecret': grpc.unary_unary_rpc_method_handler(
                    servicer.GetTSIGSecret,
                    request_deserializer=axfr__pb2.TSIGRequest.FromString,
                    response_serializer=axfr__pb2.TSIGSecret.SerializeToString,
            ),
            'CheckIPACL': grpc.unary_unary_rpc_method_handler(
                    servicer.CheckIPACL,
                    request_deserializer=axfr__pb2.IPACLRequest.FromString,
                    response_serializer=axfr__pb2.IPACLResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'as207960.dns.axfr.AXFRService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class AXFRService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetTSIGSecret(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/as207960.dns.axfr.AXFRService/GetTSIGSecret',
            axfr__pb2.TSIGRequest.SerializeToString,
            axfr__pb2.TSIGSecret.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def CheckIPACL(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/as207960.dns.axfr.AXFRService/CheckIPACL',
            axfr__pb2.IPACLRequest.SerializeToString,
            axfr__pb2.IPACLResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
