"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

import builtins
import google.protobuf.descriptor
import google.protobuf.message
import typing

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing.final
class DnsPacket(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    MSG_FIELD_NUMBER: builtins.int
    msg: builtins.bytes
    def __init__(
        self,
        *,
        msg: builtins.bytes = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["msg", b"msg"]) -> None: ...

global___DnsPacket = DnsPacket

@typing.final
class ClearCache(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    LABEL_FIELD_NUMBER: builtins.int
    DNS_CLASS_FIELD_NUMBER: builtins.int
    RECORD_TYPE_FIELD_NUMBER: builtins.int
    label: builtins.str
    dns_class: builtins.int
    record_type: builtins.int
    def __init__(
        self,
        *,
        label: builtins.str = ...,
        dns_class: builtins.int = ...,
        record_type: builtins.int = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["dns_class", b"dns_class", "label", b"label", "record_type", b"record_type"]) -> None: ...

global___ClearCache = ClearCache
