# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import dns_pb2 as dns__pb2

GRPC_GENERATED_VERSION = '1.74.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in dns_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class DnsServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Query = channel.unary_unary(
                '/coredns.dns.DnsService/Query',
                request_serializer=dns__pb2.DnsPacket.SerializeToString,
                response_deserializer=dns__pb2.DnsPacket.FromString,
                _registered_method=True)
        self.AXFRQuery = channel.unary_stream(
                '/coredns.dns.DnsService/AXFRQuery',
                request_serializer=dns__pb2.DnsPacket.SerializeToString,
                response_deserializer=dns__pb2.DnsPacket.FromString,
                _registered_method=True)
        self.UpdateQuery = channel.unary_unary(
                '/coredns.dns.DnsService/UpdateQuery',
                request_serializer=dns__pb2.DnsPacket.SerializeToString,
                response_deserializer=dns__pb2.DnsPacket.FromString,
                _registered_method=True)
        self.NotifyQuery = channel.unary_unary(
                '/coredns.dns.DnsService/NotifyQuery',
                request_serializer=dns__pb2.DnsPacket.SerializeToString,
                response_deserializer=dns__pb2.DnsPacket.FromString,
                _registered_method=True)


class DnsServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Query(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AXFRQuery(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateQuery(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def NotifyQuery(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_DnsServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Query': grpc.unary_unary_rpc_method_handler(
                    servicer.Query,
                    request_deserializer=dns__pb2.DnsPacket.FromString,
                    response_serializer=dns__pb2.DnsPacket.SerializeToString,
            ),
            'AXFRQuery': grpc.unary_stream_rpc_method_handler(
                    servicer.AXFRQuery,
                    request_deserializer=dns__pb2.DnsPacket.FromString,
                    response_serializer=dns__pb2.DnsPacket.SerializeToString,
            ),
            'UpdateQuery': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateQuery,
                    request_deserializer=dns__pb2.DnsPacket.FromString,
                    response_serializer=dns__pb2.DnsPacket.SerializeToString,
            ),
            'NotifyQuery': grpc.unary_unary_rpc_method_handler(
                    servicer.NotifyQuery,
                    request_deserializer=dns__pb2.DnsPacket.FromString,
                    response_serializer=dns__pb2.DnsPacket.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'coredns.dns.DnsService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('coredns.dns.DnsService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class DnsService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Query(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/coredns.dns.DnsService/Query',
            dns__pb2.DnsPacket.SerializeToString,
            dns__pb2.DnsPacket.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AXFRQuery(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/coredns.dns.DnsService/AXFRQuery',
            dns__pb2.DnsPacket.SerializeToString,
            dns__pb2.DnsPacket.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateQuery(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/coredns.dns.DnsService/UpdateQuery',
            dns__pb2.DnsPacket.SerializeToString,
            dns__pb2.DnsPacket.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def NotifyQuery(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/coredns.dns.DnsService/NotifyQuery',
            dns__pb2.DnsPacket.SerializeToString,
            dns__pb2.DnsPacket.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
