"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
import builtins
import google.protobuf.descriptor
import google.protobuf.message
import typing
import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor = ...

class DnsPacket(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    MSG_FIELD_NUMBER: builtins.int
    msg: builtins.bytes = ...

    def __init__(self,
        *,
        msg : builtins.bytes = ...,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal[u"msg",b"msg"]) -> None: ...
global___DnsPacket = DnsPacket

class ClearCache(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    LABEL_FIELD_NUMBER: builtins.int
    DNS_CLASS_FIELD_NUMBER: builtins.int
    RECORD_TYPE_FIELD_NUMBER: builtins.int
    label: typing.Text = ...
    dns_class: builtins.int = ...
    record_type: builtins.int = ...

    def __init__(self,
        *,
        label : typing.Text = ...,
        dns_class : builtins.int = ...,
        record_type : builtins.int = ...,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal[u"dns_class",b"dns_class",u"label",b"label",u"record_type",b"record_type"]) -> None: ...
global___ClearCache = ClearCache
