# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: dns.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\tdns.proto\x12\x0b\x63oredns.dns\"\x18\n\tDnsPacket\x12\x0b\n\x03msg\x18\x01 \x01(\x0c\"C\n\nClearCache\x12\r\n\x05label\x18\x01 \x01(\t\x12\x11\n\tdns_class\x18\x02 \x01(\r\x12\x13\n\x0brecord_type\x18\x03 \x01(\r2\xc3\x01\n\nDnsService\x12\x37\n\x05Query\x12\x16.coredns.dns.DnsPacket\x1a\x16.coredns.dns.DnsPacket\x12=\n\tAXFRQuery\x12\x16.coredns.dns.DnsPacket\x1a\x16.coredns.dns.DnsPacket0\x01\x12=\n\x0bUpdateQuery\x12\x16.coredns.dns.DnsPacket\x1a\x16.coredns.dns.DnsPacketB\x04Z\x02pbb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'dns_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z\002pb'
  _DNSPACKET._serialized_start=26
  _DNSPACKET._serialized_end=50
  _CLEARCACHE._serialized_start=52
  _CLEARCACHE._serialized_end=119
  _DNSSERVICE._serialized_start=122
  _DNSSERVICE._serialized_end=317
# @@protoc_insertion_point(module_scope)
